-- ============================================================
-- DivineConnect Temple Seed Script - Phase 1 Expansion
-- Adds ~96 additional famous temples (104 -> ~200 total)
-- UPSERT logic: safe to run multiple times (idempotent)
-- Conflict target: (name, location_city) - requires unique index, created below
-- ============================================================

-- Ensure a unique index exists so ON CONFLICT (name, location_city) works
CREATE UNIQUE INDEX IF NOT EXISTS uq_temples_name_city ON temples (name, location_city);

INSERT INTO temples (
    name, alternate_name, deity, other_deities, category,
    location_city, location_state, full_address,
    latitude, longitude,
    timings_general, timings_morning_aarti, timings_evening_aarti,
    entry_fee, dress_code, famous_for, best_time_visit, festivals,
    contact_phone, website, image_url, tag, rating, reviews,
    pincode, nearest_railway, nearest_airport,
    history, special_darshan, timings_closed_on
) VALUES
(
  'Krishna Balaram Mandir (ISKCON)', 'ISKCON Vrindavan',
  'Lord Krishna', ARRAY['Balarama','Radha'],
  'Vaishnava',
  'Vrindavan', 'Uttar Pradesh',
  'Bhaktivedanta Swami Marg, Raman Reti, Vrindavan, Uttar Pradesh 281121',
  '27.5827', '77.6701',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Founded by ISKCON; tomb of Srila Prabhupada; vibrant evening kirtans',
  'October to March',
  ARRAY['Janmashtami','Gaura Purnima','Radhashtami'],
  '+91-9253850315', 'www.iskconvrindavan.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.7', 45200,
  '281121', 'Mathura Junction (10 km)', 'Agra Airport (70 km)',
  'Established in 1975 by the International Society for Krishna Consciousness, the temple houses the samadhi of founder Srila Prabhupada and is a major centre for Krishna devotion worldwide.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Sankat Mochan Hanuman Temple', 'Sankat Mochan Mandir',
  'Lord Hanuman', ARRAY[]::TEXT[],
  'Hanuman',
  'Varanasi', 'Uttar Pradesh',
  'Sankat Mochan Rd, Bhelupur, Varanasi, Uttar Pradesh 221005',
  '25.2847', '83.0064',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Founded by Goswami Tulsidas; large monkey population; Tuesday and Saturday crowds',
  'October to March',
  ARRAY['Hanuman Jayanti','Tulsidas Jayanti'],
  '+91-6721231013', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 38900,
  '221005', 'Varanasi Junction (6 km)', 'Lal Bahadur Shastri International Airport (22 km)',
  'Established by the saint-poet Tulsidas in the 16th century at the spot where he is said to have had a vision of Hanuman.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Mankameshwar Temple', 'Mankameshwar Mandir',
  'Lord Shiva', ARRAY['Parvati'],
  'Shiva',
  'Lucknow', 'Uttar Pradesh',
  'Mankameshwar Rd, Aminabad, Lucknow, Uttar Pradesh 226003',
  '26.8645', '80.9118',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the oldest Shiva temples in Lucknow on the banks of river Gomti',
  'October to March',
  ARRAY['Maha Shivratri','Shravan Month'],
  '+91-7921229905', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 15600,
  '226003', 'Lucknow Charbagh (3 km)', 'Chaudhary Charan Singh Airport (12 km)',
  'Believed to be over 100 years older than the city of Lucknow itself, this ancient temple on the Gomti riverbank is closely linked with the Nath sect of saints.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Naimisharanya Temple', 'Naimisharanya Dham',
  'Lord Vishnu', ARRAY['Devi Lalita'],
  'Vaishnava',
  'Sitapur', 'Uttar Pradesh',
  'Naimisharanya, Sitapur, Uttar Pradesh 261401',
  '27.6167', '80.4833',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the 24 Vana Tirthas; site of Chakra Tirth and Lalita Devi Shakti Peeth',
  'October to March',
  ARRAY['Kartik Purnima','Navaratri'],
  '+91-3952690464', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 9800,
  '261401', 'Naimisharanya Railway Station (1 km)', 'Lucknow Airport (90 km)',
  'According to the Puranas, Naimisharanya is where the great sages performed a 12-year-long Satsang and where the Puranas were first narrated.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Kamadgiri Temple', 'Kamadgiri Parvat',
  'Lord Rama', ARRAY['Bharat','Lakshman'],
  'Vaishnava',
  'Chitrakoot', 'Uttar Pradesh',
  'Kamadgiri, Chitrakoot, Uttar Pradesh 210204',
  '25.1990', '80.8330',
  '5:00 AM - 12:00 PM, 2:30 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Sacred hill circumambulated by pilgrims; Lord Rama''s exile residence',
  'October to March',
  ARRAY['Diwali','Ram Navami','Deepotsav'],
  '+91-6490015723', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 12400,
  '210204', 'Chitrakoot Dham Karwi (15-20 km)', 'Allahabad Airport ( 108–115 km)',
  'Chitrakoot is closely associated with the period Lord Rama spent in exile, and Kamadgiri hill is considered the most sacred spot, circled barefoot by devotees.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Gorakhnath Temple', 'Gorakhnath Mandir',
  'Guru Gorakhnath', ARRAY['Lord Shiva'],
  'Nath Sampradaya',
  'Gorakhpur', 'Uttar Pradesh',
  'Gorakhnath Rd, Gorakhpur, Uttar Pradesh 273015',
  '26.7762', '83.3736',
  '3:00 AM - 11:30 PM, 4:00 PM - 9:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Headquarters of the Nath sect; massive Makar Sankranti mela',
  'October to March',
  ARRAY['Makar Sankranti','Nag Panchami'],
  '+91-8983379404', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 21300,
  '273015', 'Gorakhpur Junction (5 km)', 'Gorakhpur Airport (12 km)',
  'Named after the yogi saint Gorakhnath, this temple is the spiritual headquarters of the Nath Sampradaya and hosts one of the largest Khichdi melas in India during Makar Sankranti.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Durga Kund Temple', 'Durga Mandir Varanasi',
  'Goddess Durga', ARRAY[]::TEXT[],
  'Devi',
  'Varanasi', 'Uttar Pradesh',
  'Durgakund Rd, Varanasi, Uttar Pradesh 221010',
  '25.2913', '82.9959',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'North Indian Nagara style temple painted ochre-red; adjoining temple tank',
  'October to March',
  ARRAY['Navratri','Durga Puja'],
  '+91-3791142735', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 18700,
  '221010', 'Varanasi Junction (5 km)', 'Lal Bahadur Shastri International Airport (20 km)',
  'Built in the 18th century by the Maharani of Bengal Bhabani, the temple is famous for its distinctive red ochre colour and the large rectangular tank (kund) beside it.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Sarnath Buddhist Temple', 'Mulagandha Kuti Vihara',
  'Lord Buddha', ARRAY[]::TEXT[],
  'Buddhist',
  'Sarnath', 'Uttar Pradesh',
  'Sarnath, Varanasi, Uttar Pradesh 221007',
  '25.3811', '83.0238',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Site of Buddha''s first sermon; Dhamek Stupa nearby',
  'October to March',
  ARRAY['Buddha Purnima'],
  '+91-5626329669', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 27600,
  '221007', 'Sarnath Railway Station (1 km)', 'Lal Bahadur Shastri International Airport (25 km)',
  'Sarnath is one of the four most sacred Buddhist sites, marking the location where Gautama Buddha first taught the Dharma after attaining enlightenment.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Thillai Nataraja Temple', 'Chidambaram Temple',
  'Lord Shiva (Nataraja)', ARRAY['Goddess Sivakami'],
  'Shiva',
  'Chidambaram', 'Tamil Nadu',
  'Chidambaram, Cuddalore District, Tamil Nadu 608001',
  '11.3994', '79.6936',
  '6:00 AM - 12:00 PM, 5:00 PM - 10:00 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Cosmic dance form of Shiva as Nataraja; one of the Pancha Sabha temples',
  'October to March',
  ARRAY['Natyanjali Festival','Arudra Darshan','Maha Shivratri'],
  '+91-4144-222567', 'www.chidambaramtemple.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.8', 52300,
  '608001', 'Chidambaram Railway Station (1 km)', 'Puducherry Airport (75 km)',
  'One of the most ancient and significant temples in Tamil Nadu, dedicated to Shiva in his form as the cosmic dancer Nataraja, representing the element of Akasha (space/ether).',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Arunachaleswarar Temple', 'Annamalaiyar Temple',
  'Lord Shiva', ARRAY['Parvati as Unnamalai'],
  'Shiva',
  'Tiruvannamalai', 'Tamil Nadu',
  'Tiruvannamalai, Tamil Nadu 606601',
  '12.2253', '79.0747',
  '5:30 AM - 12:30 PM, 3:30 PM - 9:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Represents the element of Fire among Pancha Bhuta Stalas; Karthigai Deepam festival',
  'October to March',
  ARRAY['Karthigai Deepam','Girivalam','Maha Shivratri'],
  '+91-4175-252060', 'www.arunachaleswarar.org',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.8', 61500,
  '606601', 'Tiruvannamalai Railway Station (2 km)', 'Chennai International Airport (185 km)',
  'One of the largest temple complexes in India, dedicated to Shiva as Agni Lingam. The annual Karthigai Deepam sees a giant beacon lit atop Arunachala hill visible for miles.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Kapaleeshwarar Temple', 'Kapaleeshwarar Mandir',
  'Lord Shiva', ARRAY['Goddess Karpagambal'],
  'Shiva',
  'Chennai', 'Tamil Nadu',
  'Mylapore, Chennai, Tamil Nadu 600004',
  '13.0337', '80.2697',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Iconic Dravidian gopuram in the heart of Mylapore; Panguni Peruvizha festival',
  'October to March',
  ARRAY['Panguni Peruvizha','Arubathimoovar Festival'],
  '+91-7820292977', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.7', 43200,
  '600004', 'Mylapore MRTS Station (1 km)', 'Chennai International Airport (12 km)',
  'A classic example of Dravidian architecture, this temple is believed to have originally stood by the seashore before being rebuilt at its present Mylapore site during the Vijayanagar period.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Ranganathaswamy Temple', 'Srirangam Temple',
  'Lord Vishnu (Ranganatha)', ARRAY['Goddess Ranganayaki'],
  'Vaishnava',
  'Srirangam', 'Tamil Nadu',
  'Srirangam, Tiruchirappalli, Tamil Nadu 620006',
  '10.8624', '78.6905',
  '6:00 AM - 1:00 PM, 3:15 PM - 8:45 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Largest functioning Hindu temple complex in the world; 7 prakarams and 21 gopurams',
  'October to March',
  ARRAY['Vaikunta Ekadasi','Chithirai Festival'],
  '+91-431-2431246', 'www.srirangam.tnhrce.in',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.8', 58700,
  '620006', 'Srirangam Railway Station (1 km)', 'Tiruchirappalli International Airport (10 km)',
  'One of the most important Vaishnava temples (Divya Desams), Srirangam''s vast complex covers over 156  acres with seven concentric enclosures, the outermost forming a small town.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Arulmigu Dhandayuthapani Swamy Temple', 'Palani Murugan Temple',
  'Lord Murugan', ARRAY[]::TEXT[],
  'Murugan',
  'Palani', 'Tamil Nadu',
  'Palani, Dindigul District, Tamil Nadu 624601',
  '10.4495', '77.5198',
  '6:00 AM - 1:00 PM, 2:30 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Hilltop shrine reached by winic incline car/steps; one of the six abodes of Murugan',
  'October to March',
  ARRAY['Thaipusam','Panguni Uthiram'],
  '+91-4545-241223', 'www.palanimurugantemple.org',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 49600,
  '624601', 'Palani Railway Station (2 km)', 'Coimbatore International Airport (95 km)',
  'One of the Aaru Padai Veedu (six abodes) of Lord Murugan, situated atop the Sivagiri hill. The presiding deity is depicted as an ascetic, having renounced worldly attire.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Ekambareswarar Temple', 'Ekambaranathar Temple',
  'Lord Shiva', ARRAY['Goddess Kamakshi'],
  'Shiva',
  'Kanchipuram', 'Tamil Nadu',
  'Kanchipuram, Tamil Nadu 631502',
  '12.8447', '79.7036',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Represents the element of Earth among Pancha Bhuta Stalas; 3500-year-old mango tree',
  'October to March',
  ARRAY['Panguni Brahmotsavam','Maha Shivratri'],
  '+91-5369034455', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 29800,
  '631502', 'Kanchipuram Railway Station (2 km)', 'Chennai International Airport (75 km)',
  'One of the Pancha Bhuta Stalas representing Earth (Prithvi), this ancient temple complex is famed for an ancient mango tree said to be over 3,500 years old with branches bearing four different flavoured mangoes.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Kamakshi Amman Temple', 'Kamakoti Peetham',
  'Goddess Kamakshi', ARRAY[]::TEXT[],
  'Devi',
  'Kanchipuram', 'Tamil Nadu',
  'Kanchipuram, Tamil Nadu 631501',
  '12.8372', '79.7036',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the Shakti Peethas; seat of Adi Shankara''s Kamakoti Peetham',
  'October to March',
  ARRAY['Navaratri','Aadi Pooram'],
  '+91-5930103346', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 34500,
  '631501', 'Kanchipuram Railway Station (1 km)', 'Chennai International Airport (70 km)',
  'Considered one of the most important Shakti Peethas, the temple is unique for housing the Sri Chakra installed by Adi Shankaracharya and is closely linked to the Kanchi Kamakoti Mutt.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Vaitheeswaran Koil', 'Pullirukkuvelur Temple',
  'Lord Shiva (Vaidyanathar)', ARRAY['Goddess Thaiyalnayaki'],
  'Navagraha',
  'Vaitheeswaran Koil', 'Tamil Nadu',
  'Vaitheeswaran Koil, Mayiladuthurai District, Tamil Nadu 609117',
  '11.1769', '79.7917',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Healing temple of Lord Shiva as the divine physician; Navagraha temple for Mars (Angaraka)',
  'October to March',
  ARRAY['Masi Magam','Skanda Sashti'],
  '+91-3958856721', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 17600,
  '609117', 'Vaitheeswaran Koil Railway Station (1 km)', 'Tiruchirappalli International Airport (130 km)',
  'Devotees visit this temple seeking cures for ailments, as Shiva here takes the form of Vaidyanathar, the divine healer, and the temple is also one of the nine Navagraha shrines representing Mars.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Nellaiappar Temple', 'Nellaiappar-Kanthimathi Temple',
  'Lord Shiva', ARRAY['Goddess Kanthimathi'],
  'Shiva',
  'Tirunelveli', 'Tamil Nadu',
  'Tirunelveli, Tamil Nadu 627001',
  '8.7223', '77.7016',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Famous musical pillars; twin temple complex joined by Sangili Mandapam',
  'October to March',
  ARRAY['Float Festival (Teppam)','Aadi Perukku'],
  '+91-4415784593', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 21900,
  '627001', 'Tirunelveli Junction (2 km)', 'Tuticorin Airport (35 km)',
  'Renowned for its ''musical pillars'' that produce different musical notes when tapped, this twin-temple complex dedicated to Shiva and Parvati is linked by a unique chain-mandapam.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Srikalahasti Temple', 'Sri Kalahasteeswara Swamy Temple',
  'Lord Shiva', ARRAY['Goddess Gnana Prasunamba'],
  'Vayu Lingam',
  'Srikalahasti', 'Andhra Pradesh',
  'Srikalahasti, Chittoor District, Andhra Pradesh 517644',
  '13.7505', '79.7016',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Represents the element of Air among Pancha Bhuta Stalas; Rahu-Ketu pariharam',
  'October to March',
  ARRAY['Maha Shivratri','Rahu Ketu Pooja Days'],
  '+91-9651386898', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.6', 38400,
  '517644', 'Srikalahasti Railway Station (1 km)', 'Tirupati Airport (35 km)',
  'One of the Pancha Bhuta Stalas representing Vayu (air), this temple is especially famous for Rahu-Ketu dosha pariharam rituals performed for devotees from across India.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Annavaram Satyanarayana Swamy Temple', 'Annavaram Temple',
  'Lord Satyanarayana (Vishnu)', ARRAY[]::TEXT[],
  'Vaishnava',
  'Annavaram', 'Andhra Pradesh',
  'Annavaram, East Godavari District, Andhra Pradesh 533406',
  '17.7574', '82.4067',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Hilltop temple on Ratnagiri hill overlooking Pampa river; Satyanarayana Vratam',
  'October to March',
  ARRAY['Kartika Masam','Ratha Saptami'],
  '+91-9084361741', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 33200,
  '533406', 'Annavaram Railway Station (1 km)', 'Visakhapatnam Airport (110 km)',
  'Situated atop Ratnagiri hill, this temple dedicated to Satyanarayana Swamy (a combined form of Vishnu, Shiva and Brahma) is famous for devotees performing the Satyanarayana Vratam.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Kanaka Durga Temple', 'Vijayawada Durga Temple',
  'Goddess Durga', ARRAY[]::TEXT[],
  'Devi',
  'Vijayawada', 'Andhra Pradesh',
  'Indrakeeladri Hill, Vijayawada, Andhra Pradesh 520001',
  '16.5152', '80.6128',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Hilltop shrine on Indrakeeladri overlooking the Krishna river; major Dasara hub',
  'October to March',
  ARRAY['Dasara Navaratri','Lakshmi Pooja'],
  '+91-5538500920', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 42100,
  '520001', 'Vijayawada Junction (3 km)', 'Vijayawada Airport (20 km)',
  'Perched on Indrakeeladri hill above the Krishna river, this Shakti temple is one of the few where the goddess is believed to have manifested on her own (Swayambhu).',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Ahobilam Narasimha Temple', 'Nava Narasimha Kshetram',
  'Lord Narasimha (Vishnu)', ARRAY['Goddess Chenchulakshmi'],
  'Vaishnava',
  'Ahobilam', 'Andhra Pradesh',
  'Ahobilam, Nandyal District, Andhra Pradesh 518543',
  '15.1667', '78.7167',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Nine forms of Narasimha shrines spread across the Nallamala hills',
  'October to March',
  ARRAY['Brahmotsavam','Narasimha Jayanti'],
  '+91-9404872736', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 15200,
  '518543', 'Nandyal Railway Station (50 km)', 'Tirupati Airport (200 km)',
  'A cluster of nine ancient temples nestled in the forested Nallamala hills, each dedicated to a different form (avatar) of Lord Narasimha.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Mangaladevi Temple Mangalore', 'Mangaladevi Mandir',
  'Goddess Mangaladevi', ARRAY[]::TEXT[],
  'Devi',
  'Mangalore', 'Karnataka',
  'Bolar, Mangalore, Karnataka 575001',
  '12.8635', '74.8420',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Temple after which the city of Mangaluru is named',
  'October to March',
  ARRAY['Navaratri','Chaitra Vishu'],
  '+91-1075658573', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 11300,
  '575001', 'Mangalore Central (2 km)', 'Mangalore International Airport (15 km)',
  'Believed to have been consecrated by the Nath yogi Matsyendranath in the 9th century, the city of Mangaluru derives its name from this temple''s presiding deity.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Murudeshwara Temple', 'Murudeshwar Shiva Temple',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Shiva',
  'Murudeshwar', 'Karnataka',
  'Murudeshwar, Bhatkal Taluk, Karnataka 581350',
  '14.0942', '74.4859',
  '6:00 AM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the tallest Shiva statues in the world (123 ft) overlooking the Arabian Sea',
  'October to March',
  ARRAY['Maha Shivratri'],
  '+91-8385-260210', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 39800,
  '581350', 'Murudeshwar Railway Station (2 km)', 'Mangalore International Airport (150 km)',
  'Home to one of the world''s tallest Shiva statues, standing 123 feet tall on a hillock surrounded on three sides by the Arabian Sea, with a 20-storey gopura entrance.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Kukke Subramanya Temple', 'Subramanya Temple',
  'Lord Subramanya (Karthikeya)', ARRAY['Vasuki - Serpent God'],
  'Naga',
  'Subramanya', 'Karnataka',
  'Kukke Subramanya, Sullia Taluk, Karnataka 574238',
  '12.6167', '75.4833',
  '5:00 AM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Famous for Sarpa Samskara and Naga Pratishtha rituals; lush Western Ghats setting',
  'October to March',
  ARRAY['Champa Shasti','Naga Panchami'],
  '+91-8257-258232', 'www.kukkesubramanya.in',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 28700,
  '574238', 'Subrahmanya Road Railway Station (8 km)', 'Mangalore International Airport (105 km)',
  'Nestled amid the Western Ghats, this temple is dedicated to Lord Subramanya in association with the serpent god Vasuki and is one of the most important centres for Sarpa Dosha remedial rituals.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Sri Krishna Matha Udupi', 'Udupi Krishna Temple',
  'Lord Krishna', ARRAY[]::TEXT[],
  'Vaishnava',
  'Udupi', 'Karnataka',
  'Car Street, Udupi, Karnataka 576101',
  '13.3409', '74.7421',
  '5:30 AM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Founded by Madhvacharya; famous Kanaka Kindi window; origin of Udupi cuisine',
  'October to March',
  ARRAY['Paryaya Festival','Krishna Janmashtami'],
  '+91-820-2522728', 'www.krishnamatha.in',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 31200,
  '576101', 'Udupi Railway Station (3 km)', 'Mangalore International Airport (60 km)',
  'Established by the 13th-century philosopher Madhvacharya, the temple is famous for the Kanakana Kindi, a small window through which the lower-caste saint-poet Kanakadasa is said to have viewed the deity.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Mahabaleshwar Temple Gokarna', 'Gokarna Shiva Temple',
  'Lord Shiva (Atmalinga)', ARRAY[]::TEXT[],
  'Shiva',
  'Gokarna', 'Karnataka',
  'Gokarna, Uttara Kannada, Karnataka 581326',
  '14.5497', '74.3197',
  '6:00 AM - 1:00 PM, 5:00 PM - 8:00 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Houses the sacred Atmalinga; coastal pilgrimage town',
  'October to March',
  ARRAY['Maha Shivratri','Karthika Purnima'],
  '+91-2761266129', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 19500,
  '581326', 'Gokarna Road Railway Station (8 km)', 'Goa International Airport (140 km)',
  'According to legend, this temple houses the Atmalinga that Lord Ganesha tricked Ravana into placing on the ground here, making it one of the holiest sites for Shaivites in South India.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Chamundeshwari Temple', 'Chamundi Hills Temple',
  'Goddess Chamundeshwari (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Mysore', 'Karnataka',
  'Chamundi Hills, Mysore, Karnataka 570010',
  '12.2724', '76.6730',
  '7:30 AM - 2:00 PM, 3:30 PM - 9:00 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Hilltop temple overlooking Mysore city; 1000-step ancient stairway with Nandi statue',
  'October to March',
  ARRAY['Dasara (Mysore)','Navaratri'],
  '+91-821-2405444', 'www.chamundeshwaritemple.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 36400,
  '570010', 'Mysore Junction (13 km)', 'Mysore Airport (11 km)',
  'Perched atop Chamundi Hills overlooking Mysore, this temple is dedicated to the fierce goddess Chamundeshwari, the tutelary deity of the Mysore royal family, and is reached via a stairway of nearly 1,000 steps.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Virupaksha Temple Hampi', 'Hampi Virupaksha Temple',
  'Lord Shiva (Virupaksha)', ARRAY['Goddess Pampa'],
  'Shiva',
  'Hampi', 'Karnataka',
  'Hampi, Ballari District, Karnataka 583239',
  '15.3350', '76.4600',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Part of UNESCO World Heritage site; still-functioning ancient temple amid ruins',
  'October to March',
  ARRAY['Virupaksha Car Festival','Hampi Utsav'],
  '+91-9470213570', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.7', 24600,
  '583239', 'Hospet Junction (13 km)', 'Hubli Airport (165 km)',
  'Part of the UNESCO World Heritage Hampi Group of Monuments, this is one of the oldest continuously functioning temples in India, dating back to the 7th century.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Trimbakeshwar Temple', 'Tryambakeshwar Jyotirlinga',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Jyotirlinga',
  'Nashik', 'Maharashtra',
  'Trimbak, Nashik District, Maharashtra 422212',
  '19.9319', '73.5301',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the 12 Jyotirlingas; unique three-faced linga representing Brahma-Vishnu-Shiva',
  'October to March',
  ARRAY['Maha Shivratri','Kumbh Mela (Nashik)'],
  '+91-9847468567', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 41200,
  '422212', 'Nashik Road Railway Station (28 km)', 'Nashik Airport (35 km)',
  'One of the twelve Jyotirlingas, the presiding deity here is unusual in having three faces embodying Brahma, Vishnu and Shiva, and the temple is the source of the sacred Godavari river.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Bhimashankar Temple', 'Bhimashankar Jyotirlinga',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Jyotirlinga',
  'Pune', 'Maharashtra',
  'Bhimashankar, Pune District, Maharashtra 410509',
  '19.0728', '73.5350',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the 12 Jyotirlingas set in the Sahyadri hills wildlife sanctuary',
  'October to March',
  ARRAY['Maha Shivratri','Tripuri Purnima'],
  '+91-6234767799', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 22300,
  '410509', 'Pune Junction (110 km)', 'Pune Airport (125 km)',
  'Located within the Bhimashankar Wildlife Sanctuary in the Sahyadri ranges, this Jyotirlinga temple is also the source of the river Bhima.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Grishneshwar Temple', 'Ghrishneshwar Jyotirlinga',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Jyotirlinga',
  'Aurangabad', 'Maharashtra',
  'Verul, Aurangabad District, Maharashtra 431102',
  '20.0233', '75.1797',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the 12 Jyotirlingas, located near the Ellora Caves UNESCO site',
  'October to March',
  ARRAY['Maha Shivratri'],
  '+91-9658734236', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 18900,
  '431102', 'Aurangabad Railway Station (30 km)', 'Aurangabad Airport (35 km)',
  'The smallest yet historically significant of the twelve Jyotirlingas, situated near the famed Ellora Caves and rebuilt in its present form by Ahilyabai Holkar in the 18th century.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Tulja Bhavani Temple', 'Tuljapur Bhavani Mandir',
  'Goddess Tulja Bhavani (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Tuljapur', 'Maharashtra',
  'Tuljapur, Osmanabad District, Maharashtra 413601',
  '18.0167', '76.0833',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Family deity (Kuldevi) of Chhatrapati Shivaji Maharaj',
  'October to March',
  ARRAY['Navaratri','Chaitra Yatra'],
  '+91-9932609107', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 29400,
  '413601', 'Solapur Railway Station (45 km)', 'Pune Airport (250 km)',
  'One of the most revered Shakti Peethas in Maharashtra and the family deity of Chhatrapati Shivaji Maharaj, who is said to have received his sword Bhavani from the goddess.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Vitthal Rukmini Temple', 'Pandharpur Vitthal Temple',
  'Lord Vitthal (Krishna)', ARRAY['Goddess Rukmini'],
  'Vaishnava',
  'Pandharpur', 'Maharashtra',
  'Pandharpur, Solapur District, Maharashtra 413304',
  '17.6792', '75.3294',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Centre of the Bhakti movement; massive Ashadhi Ekadashi Wari pilgrimage on foot',
  'October to March',
  ARRAY['Ashadhi Ekadashi Wari','Kartiki Ekadashi'],
  '+91-3009022621', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 47800,
  '413304', 'Pandharpur Railway Station (1 km)', 'Pune Airport (200 km)',
  'The spiritual heart of Maharashtra''s Bhakti movement, this temple sees millions of pilgrims (Warkaris) walk hundreds of kilometres on foot for the Ashadhi Ekadashi festival.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Khandoba Temple Jejuri', 'Jejuri Khandoba Mandir',
  'Lord Khandoba (Shiva form)', ARRAY[]::TEXT[],
  'Folk Deity',
  'Jejuri', 'Maharashtra',
  'Jejuri, Pune District, Maharashtra 412303',
  '18.2783', '74.1606',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Famous for turmeric (bhandara) showers during festivals; hilltop fort-temple',
  'October to March',
  ARRAY['Champa Shashti','Somvati Amavasya'],
  '+91-3375599517', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 14200,
  '412303', 'Jejuri Railway Station (1 km)', 'Pune Airport (50 km)',
  'Devotees throw and shower each other with turmeric powder (bhandara) at this hilltop fort-temple dedicated to Khandoba, a regional folk deity considered a form of Shiva.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Ambaji Temple', 'Arasuri Ambaji Mata Mandir',
  'Goddess Amba (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Ambaji', 'Gujarat',
  'Ambaji, Banaskantha District, Gujarat 385110',
  '24.2078', '72.8508',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the 51 Shakti Peethas; aniconic worship with a Yantra instead of an idol',
  'October to March',
  ARRAY['Bhadarvi Poonam','Navaratri'],
  '+91-9083897362', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 33700,
  '385110', 'Abu Road Railway Station (20 km)', 'Ahmedabad Airport (180 km)',
  'One of the principal Shakti Peethas of India, unique in that there is no idol in the sanctum — the goddess is worshipped in the form of a Vishwa Yantra.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Pavagadh Kalika Mata Temple', 'Mahakali Mata Pavagadh',
  'Goddess Kalika (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Pavagadh', 'Gujarat',
  'Pavagadh Hill, Panchmahal District, Gujarat 389360',
  '22.4836', '73.5328',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'UNESCO World Heritage Champaner-Pavagadh complex; ropeway to hilltop shrine',
  'October to March',
  ARRAY['Navaratri','Chaitra Poonam'],
  '+91-3155974088', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 21800,
  '389360', 'Champaner Road Railway Station (5 km)', 'Vadodara Airport (50 km)',
  'Located atop Pavagadh Hill within the UNESCO World Heritage Champaner-Pavagadh Archaeological Park, reached by an aerial ropeway, this Shakti Peeth attracts massive Navaratri crowds.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Bahuchara Mata Temple', 'Bahucharaji Mandir',
  'Goddess Bahuchara Mata', ARRAY[]::TEXT[],
  'Devi',
  'Becharaji', 'Gujarat',
  'Becharaji, Mehsana District, Gujarat 384210',
  '23.5333', '72.0833',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Important Shakti Peeth especially revered by the transgender community',
  'October to March',
  ARRAY['Navaratri','Bhadarvi Poonam'],
  '+91-5356628206', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 9600,
  '384210', 'Becharaji Railway Station (1 km)', 'Ahmedabad Airport (110 km)',
  'A significant Shakti Peeth in north Gujarat, the goddess here is particularly venerated as a patron deity by the transgender (Hijra) community across India.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Shamlaji Temple', 'Gadadhar Shamlaji Mandir',
  'Lord Vishnu (Shamlaji)', ARRAY[]::TEXT[],
  'Vaishnava',
  'Shamlaji', 'Gujarat',
  'Shamlaji, Aravalli District, Gujarat 383215',
  '23.7333', '73.3833',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Ancient temple on the banks of the Meshwo river; popular Kartik Purnima fair',
  'October to March',
  ARRAY['Kartik Purnima Mela'],
  '+91-2485205776', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.4', 7300,
  '383215', 'Shamlaji Road Railway Station (2 km)', 'Ahmedabad Airport (130 km)',
  'An ancient temple dedicated to a form of Vishnu, located on the banks of the Meshwo River, famous for its annual Kartik Purnima fair attracting tribal communities from across the region.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Modhera Sun Temple', 'Surya Mandir Modhera',
  'Surya (Sun God)', ARRAY[]::TEXT[],
  'Surya',
  'Modhera', 'Gujarat',
  'Modhera, Mehsana District, Gujarat 384212',
  '23.5859', '72.1316',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  '11th-century sun temple aligned for equinox sunrise; Modhera Dance Festival',
  'October to March',
  ARRAY['Uttarardh Mahotsav','Modhera Dance Festival'],
  '+91-9875862778', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 16200,
  '384212', 'Mehsana Railway Station (25 km)', 'Ahmedabad Airport (100 km)',
  'Built in 1026-27 CE by King Bhimdev I of the Solanki dynasty, this UNESCO-recognised temple is designed so that the rising sun''s rays illuminate the sanctum at equinoxes.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Lingaraj Temple', 'Lingaraja Mandir',
  'Lord Shiva (Harihara)', ARRAY['Vishnu'],
  'Shiva',
  'Bhubaneswar', 'Odisha',
  'Old Town, Bhubaneswar, Odisha 751002',
  '20.2382', '85.8316',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Largest temple in Bhubaneswar; combined form of Shiva and Vishnu (Harihara)',
  'October to March',
  ARRAY['Rath Yatra (Lingaraj)','Maha Shivratri','Ashokashtami'],
  '+91-8152886798', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 28900,
  '751002', 'Bhubaneswar Railway Station (4 km)', 'Biju Patnaik International Airport (8 km)',
  'One of the oldest and largest temples in Bhubaneswar, the 11th-century Lingaraja temple represents Tribhubaneswar, worshipped as both Shiva and Vishnu combined (Harihara).',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Konark Sun Temple', 'Surya Mandir Konark',
  'Surya (Sun God)', ARRAY[]::TEXT[],
  'Surya',
  'Konark', 'Odisha',
  'Konark, Puri District, Odisha 752111',
  '19.8876', '86.0945',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'UNESCO World Heritage Site shaped as a colossal stone chariot with 24 wheels',
  'October to March',
  ARRAY['Konark Dance Festival','Chandrabhaga Mela'],
  '+91-2580471301', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.8', 52600,
  '752111', 'Puri Railway Station (35 km)', 'Biju Patnaik International Airport (65 km)',
  'A 13th-century UNESCO World Heritage Site, this temple is conceived as a gigantic stone chariot of the Sun God with twelve pairs of ornately carved wheels and seven horses.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Tara Tarini Temple', 'Tara Tarini Shakti Peeth',
  'Goddess Tara Tarini (twin goddesses)', ARRAY[]::TEXT[],
  'Devi',
  'Brahmapur', 'Odisha',
  'Purushottampur, Ganjam District, Odisha 761003',
  '19.4167', '84.7333',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Hilltop Shakti Peeth on the Rushikulya river reached by ropeway',
  'October to March',
  ARRAY['Chaitra Yatra','Mahabisuva Sankranti'],
  '+91-5228296150', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 12100,
  '761003', 'Berhampur Railway Station (12 km)', 'Bhubaneswar Airport (160 km)',
  'Perched on a hill overlooking the Rushikulya river, this Shakti Peeth is dedicated to the twin breast-shaped stones representing the goddess and is reached by a ropeway or steps.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Biraja Temple', 'Biraja Devi Mandir',
  'Goddess Biraja (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Jajpur', 'Odisha',
  'Jajpur, Odisha 755001',
  '20.8500', '86.3333',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the 51 Shakti Peethas, located on the banks of the Vaitarani river',
  'October to March',
  ARRAY['Navaratri','Makar Mela'],
  '+91-9593374276', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.4', 8700,
  '755001', 'Jajpur Keonjhar Road Railway Station (8 km)', 'Biju Patnaik International Airport (100 km)',
  'An ancient Shakti Peeth on the banks of the Vaitarani river, mentioned in the Brahma Purana, where pilgrims also perform shraddha rituals for ancestors.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),

(
  'Surkanda Devi Temple', 'Surkanda Mata Mandir',
  'Goddess Sati (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Tehri Garhwal', 'Uttarakhand',
  'Surkanda Devi, Tehri Garhwal District, Uttarakhand 249175',
  '30.4500', '78.3667',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Shakti Peeth atop a hill offering panoramic Himalayan views; 2-km trek from Kaddukhal',
  'October to March',
  ARRAY['Navaratri'],
  '+91-8357175279', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 9200,
  '249175', 'Rishikesh Railway Station (80 km)', 'Jolly Grant Airport Dehradun (85 km)',
  'One of the Shakti Peethas of the Himalayas, this temple sits atop a 2,757-metre peak offering panoramic views of major Himalayan ranges, reached via a 2 km trek.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Neelkanth Mahadev Temple', 'Neelkanth Mahadev Mandir',
  'Lord Shiva', ARRAY['Parvati'],
  'Shiva',
  'Rishikesh', 'Uttarakhand',
  'Neelkanth, Rishikesh, Uttarakhand 249302',
  '30.1167', '78.4167',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Believed to be where Shiva consumed the poison (Halahala) during Samudra Manthan',
  'October to March',
  ARRAY['Maha Shivratri','Shravan Month'],
  '+91-3874179038', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 17900,
  '249302', 'Rishikesh Railway Station (32 km)', 'Jolly Grant Airport Dehradun (45 km)',
  'Set amid forested hills above Rishikesh, this temple marks the legendary site where Shiva consumed the deadly poison Halahala churned from the cosmic ocean, turning his throat blue.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Raghunath Temple Jammu', 'Raghunath Mandir',
  'Lord Rama (Raghunath)', ARRAY['Sita','Lakshman'],
  'Vaishnava',
  'Jammu', 'Jammu and Kashmir',
  'Raghunath Bazaar, Jammu, Jammu and Kashmir 180001',
  '32.7280', '74.8642',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Largest temple complex in northern India built by Dogra rulers; seven shrines',
  'October to March',
  ARRAY['Ram Navami','Janmashtami'],
  '+91-3616778670', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 14600,
  '180001', 'Jammu Tawi Railway Station (3 km)', 'Jammu Airport (8 km)',
  'Built in the mid-19th century by Maharaja Gulab Singh and completed by Maharaja Ranbir Singh, this complex of seven shrines is one of the largest temple complexes in North India.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Kheer Bhawani Temple', 'Ragnya Devi Temple',
  'Goddess Ragnya Devi (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Ganderbal', 'Jammu and Kashmir',
  'Tulmulla, Ganderbal District, Jammu and Kashmir 191002',
  '34.2667', '74.6167',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Sacred spring temple revered by Kashmiri Pandits; spring changes colour mysteriously',
  'October to March',
  ARRAY['Kheer Bhawani Mela (Jyeshtha Ashtami)'],
  '+91-5377594542', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 11800,
  '191002', 'Srinagar Railway Station (25 km)', 'Srinagar Airport (28 km)',
  'Built around a sacred spring whose water is said to change colour as an omen, this temple is one of the most revered shrines for the Kashmiri Pandit community.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Shankaracharya Temple', 'Jyeshteshwara Temple',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Shiva',
  'Srinagar', 'Jammu and Kashmir',
  'Shankaracharya Hill, Srinagar, Jammu and Kashmir 190001',
  '34.0837', '74.8412',
  '7:00 AM - 8:00 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Ancient hilltop temple overlooking Dal Lake; visited by Adi Shankaracharya',
  'May to September',
  ARRAY['Maha Shivratri (Herath)'],
  '+91-9007913679', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 13700,
  '190001', 'Srinagar Railway Station (10 km)', 'Srinagar Airport (20 km)',
  'Perched atop a hill overlooking Srinagar and the Dal Lake, this ancient temple is believed to have been visited by the philosopher Adi Shankaracharya during his travels.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Temple is closed on Fridays as per security protocols'
),
(
  'Karni Mata Temple', 'Deshnoke Rat Temple',
  'Goddess Karni Mata (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Bikaner', 'Rajasthan',
  'Deshnoke, Bikaner District, Rajasthan 334801',
  '27.7833', '73.3400',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Famous for thousands of sacred black rats (kabbas) roaming the temple',
  'October to March',
  ARRAY['Karni Mata Fair (Navratri)'],
  '+91-1745686206', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 19400,
  '334801', 'Deshnoke Railway Station (1 km)', 'Nal Airport Bikaner (35 km)',
  'Famous worldwide for housing over 25,000 sacred black rats called ''kabbas'', believed to be reincarnated descendants of the goddess''s clan, who feed from the same plates as devotees.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Eklingji Temple', 'Eklingji Shiva Temple',
  'Lord Shiva (Eklingji)', ARRAY[]::TEXT[],
  'Shiva',
  'Udaipur', 'Rajasthan',
  'Kailashpuri, Udaipur District, Rajasthan 313202',
  '24.8333', '73.6833',
  '4:30 AM - 7:30 AM, 10:30 AM - 1:30 PM, 5:30 PM - 7:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Tutelary deity of the Mewar royal dynasty; four-faced black marble idol',
  'October to March',
  ARRAY['Maha Shivratri','Shravan Somvar'],
  '+91-1560566428', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 15200,
  '313202', 'Udaipur City Railway Station (22 km)', 'Maharana Pratap Airport Udaipur (28 km)',
  'The presiding deity of this complex is the tutelary god of the Mewar dynasty''s rulers, who traditionally styled themselves as ''Diwan'' (regents) of Eklingji.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Brahma Temple Pushkar', 'Jagatpita Brahma Mandir',
  'Lord Brahma', ARRAY['Goddess Savitri'],
  'Brahma',
  'Pushkar', 'Rajasthan',
  'Pushkar, Ajmer District, Rajasthan 305022',
  '26.4897', '74.5530',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the very few temples dedicated to Lord Brahma in India',
  'October to March',
  ARRAY['Pushkar Camel Fair','Kartik Purnima'],
  '+91-9345433870', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.6', 24800,
  '305022', 'Ajmer Junction (15 km)', 'Kishangarh Airport (45 km)',
  'One of the extremely rare temples dedicated to the creator god Brahma, set beside the holy Pushkar Lake and dating back roughly 2,000 years in its earliest form.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Govind Dev Ji Temple', 'Jaipur Govind Devji Mandir',
  'Lord Krishna (Govind Dev)', ARRAY['Radha'],
  'Vaishnava',
  'Jaipur', 'Rajasthan',
  'City Palace, Jaipur, Rajasthan 302002',
  '26.9255', '75.8235',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Royal family deity of Jaipur; idol originally from Vrindavan''s Govind Dev temple',
  'October to March',
  ARRAY['Janmashtami','Holi'],
  '+91-2986216381', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 22100,
  '302002', 'Jaipur Junction (5 km)', 'Jaipur International Airport (15 km)',
  'Considered the deity of the Jaipur royal family, the original idol was brought from the Govind Dev temple in Vrindavan to protect it from Mughal destruction in the 17th century.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Charbhuja Temple', 'Charbhujanath Mandir',
  'Lord Vishnu (Charbhuja)', ARRAY[]::TEXT[],
  'Vaishnava',
  'Rajsamand', 'Rajasthan',
  'Garhbor, Rajsamand District, Rajasthan 313324',
  '25.0500', '73.8333',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Four-armed black stone Vishnu idol; popular among Mewar farming communities',
  'October to March',
  ARRAY['Janmashtami','Holi'],
  '+91-7263379434', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.4', 6900,
  '313324', 'Rana Pratap Nagar Railway Station (40 km)', 'Maharana Pratap Airport Udaipur (75 km)',
  'An important pilgrimage site for the farming communities of the Mewar region, dedicated to a four-armed (Charbhuja) black stone image of Vishnu.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Mehandipur Balaji Temple', 'Mehandipur Hanuman Mandir',
  'Lord Hanuman (Balaji)', ARRAY[]::TEXT[],
  'Hanuman',
  'Dausa', 'Rajasthan',
  'Mehandipur, Dausa District, Rajasthan 322746',
  '26.8833', '76.6333',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Renowned for exorcism and ''peshi'' rituals to remove negative spirits',
  'October to March',
  ARRAY['Tuesday and Saturday special darshans','Hanuman Jayanti'],
  '+91-1054596033', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.4', 28900,
  '322746', 'Hindaun City Railway Station (45 km)', 'Jaipur International Airport (95 km)',
  'One of the most visited temples in North India for rituals believed to cure individuals of evil spirits and negative energies, known locally as ''peshi''.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Padmanabhaswamy Temple', 'Sree Padmanabhaswamy Temple',
  'Lord Vishnu (Padmanabha)', ARRAY[]::TEXT[],
  'Vaishnava',
  'Thiruvananthapuram', 'Kerala',
  'East Fort, Thiruvananthapuram, Kerala 695023',
  '8.4828', '76.9436',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the richest temples in the world; Dravidian gopuram and Anantha Shayana idol',
  'October to March',
  ARRAY['Alpasy Festival','Painkuni Festival'],
  '+91-9446193221', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 41600,
  '695023', 'Thiruvananthapuram Central (2 km)', 'Trivandrum International Airport (6 km)',
  'Famous for the underground vaults discovered to contain immense treasures, the temple''s deity is depicted in the Anantha Shayana posture, reclining on the serpent Adisesha.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Guruvayur Temple', 'Sree Krishna Temple Guruvayur',
  'Lord Krishna (Guruvayurappan)', ARRAY[]::TEXT[],
  'Vaishnava',
  'Guruvayur', 'Kerala',
  'Guruvayur, Thrissur District, Kerala 680101',
  '10.5945', '76.0414',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the most important Krishna temples in Kerala; famous elephant sanctuary Punnathur Kotta',
  'October to March',
  ARRAY['Guruvayur Ekadasi','Anayoottu (elephant feeding)'],
  '+91-4924995794', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 46200,
  '680101', 'Guruvayur Railway Station (1 km)', 'Cochin International Airport (80 km)',
  'Known as the ''Dwaraka of the South'', this temple''s idol is believed to have been worshipped by Lord Krishna himself and consecrated by Guru (Brihaspati) and Vayu.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Vadakkunnathan Temple', 'Thrissur Vadakkunnathan Temple',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Shiva',
  'Thrissur', 'Kerala',
  'Thrissur, Kerala 680001',
  '10.5276', '76.2144',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Centre of the famous Thrissur Pooram festival with caparisoned elephants',
  'October to March',
  ARRAY['Thrissur Pooram','Shivaratri'],
  '+91-1237769899', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.6', 27400,
  '680001', 'Thrissur Railway Station (1 km)', 'Cochin International Airport (55 km)',
  'Located at the heart of Thrissur city, this ancient temple is the focal point of the spectacular Thrissur Pooram festival, famed for its procession of caparisoned elephants and fireworks.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Chottanikkara Temple', 'Chottanikkara Bhagavathy Temple',
  'Goddess Bhagavathy (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Chottanikkara', 'Kerala',
  'Chottanikkara, Ernakulam District, Kerala 682312',
  '9.9667', '76.3667',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Believed to heal mental ailments; goddess worshipped in three forms through the day',
  'October to March',
  ARRAY['Makam Thozhal','Navaratri'],
  '+91-7763553824', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 19800,
  '682312', 'Tripunithura Railway Station (10 km)', 'Cochin International Airport (35 km)',
  'The presiding goddess is worshipped in three different forms across the day — Saraswati in the morning, Bhagavathy at noon, and Bhadrakali in the evening.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Attukal Bhagavathy Temple', 'Attukal Devi Temple',
  'Goddess Bhagavathy (Kannaki)', ARRAY[]::TEXT[],
  'Devi',
  'Thiruvananthapuram', 'Kerala',
  'Attukal, Thiruvananthapuram, Kerala 695011',
  '8.4667', '76.9500',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Holds the Guinness record for the largest gathering of women (Pongala festival)',
  'October to March',
  ARRAY['Attukal Pongala','Navaratri'],
  '+91-9381412644', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.6', 24500,
  '695011', 'Thiruvananthapuram Central (3 km)', 'Trivandrum International Airport (8 km)',
  'Holds a Guinness World Record for the Attukal Pongala festival, when millions of women gather to cook a ritual offering in the temple precincts and surrounding streets.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Ettumanoor Mahadeva Temple', 'Ettumanoor Shiva Temple',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Shiva',
  'Ettumanoor', 'Kerala',
  'Ettumanoor, Kottayam District, Kerala 686631',
  '9.6667', '76.5500',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Famous mural paintings of Nataraja; massive ''vilakku'' lamp festival',
  'October to March',
  ARRAY['Ettumanoor Vilakku','Arattu Festival'],
  '+91-2408153966', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 9700,
  '686631', 'Ettumanoor Railway Station (1 km)', 'Cochin International Airport (75 km)',
  'Renowned for its centuries-old mural paintings, particularly a celebrated depiction of Nataraja, and for its grand annual Ezharaponnana (golden elephants) procession.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Dakshineswar Kali Temple', 'Dakshineswar Kalibari',
  'Goddess Kali (Bhavatarini)', ARRAY[]::TEXT[],
  'Devi',
  'Kolkata', 'West Bengal',
  'Dakshineswar, Kolkata, West Bengal 700076',
  '22.6547', '88.3573',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Associated with saint Ramakrishna Paramahamsa; iconic Bengal Navaratna architecture',
  'October to March',
  ARRAY['Kali Puja','Durga Puja','Phalaharini Kali Puja'],
  '+91-7867647391', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 49300,
  '700076', 'Dakshineswar Railway Station (1 km)', 'Netaji Subhas Chandra Bose Airport (20 km)',
  'Built in 1855 by Rani Rashmoni, this temple is famous for its association with the 19th-century mystic Sri Ramakrishna Paramahamsa, who served as a priest here.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Kalighat Kali Temple', 'Kalighat Mandir',
  'Goddess Kali', ARRAY[]::TEXT[],
  'Devi',
  'Kolkata', 'West Bengal',
  'Kalighat, Kolkata, West Bengal 700026',
  '22.5193', '88.3424',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the 51 Shakti Peethas, situated on the banks of the Adi Ganga',
  'October to March',
  ARRAY['Kali Puja','Durga Puja'],
  '+91-6533541444', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.6', 38200,
  '700026', 'Kalighat Metro Station (0.5 km)', 'Netaji Subhas Chandra Bose Airport (18 km)',
  'One of the most sacred Shakti Peethas, where it is believed that the toes of Goddess Sati''s right foot fell, this ancient temple gives Kolkata its name.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Belur Math', 'Ramakrishna Math Belur',
  'Sri Ramakrishna', ARRAY[]::TEXT[],
  'Ramakrishna Mission',
  'Howrah', 'West Bengal',
  'Belur Math, Howrah, West Bengal 711202',
  '22.6298', '88.3554',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Headquarters of the Ramakrishna Mission founded by Swami Vivekananda; unifies temple architectural styles',
  'October to March',
  ARRAY['Durga Puja','Ramakrishna Janmotsav','Vivekananda Jayanti'],
  '+91-2109493704', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.7', 31700,
  '711202', 'Belur Math Railway Station (1 km)', 'Netaji Subhas Chandra Bose Airport (25 km)',
  'Founded by Swami Vivekananda, the main temple''s architecture deliberately blends Hindu, Christian, and Islamic motifs to symbolise the unity of all religions.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Bakreshwar Temple', 'Bakreshwar Shiva Temple',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Shakti Peeth',
  'Birbhum', 'West Bengal',
  'Bakreshwar, Birbhum District, West Bengal 731129',
  '23.8833', '87.3667',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Shakti Peeth combined with a Jyotirlinga; hot sulphur springs on site',
  'October to March',
  ARRAY['Maha Shivratri','Makar Sankranti'],
  '+91-6431862644', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.4', 8200,
  '731129', 'Siuri Railway Station (24 km)', 'Andal Airport (45 km)',
  'A unique site combining a Shakti Peeth with a Shiva shrine, famous for its natural hot sulphur springs believed to have healing properties.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Omkareshwar Temple', 'Omkareshwar Jyotirlinga',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Jyotirlinga',
  'Khandwa', 'Madhya Pradesh',
  'Mandhata Island, Khandwa District, Madhya Pradesh 450554',
  '22.2418', '76.1517',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the 12 Jyotirlingas situated on an island shaped like the ''Om'' symbol',
  'October to March',
  ARRAY['Maha Shivratri','Narmada Jayanti'],
  '+91-8390574674', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 29600,
  '450554', 'Omkareshwar Road Railway Station (12 km)', 'Indore Airport (77 km)',
  'Located on Mandhata Island in the Narmada river, the island itself is said to be shaped like the sacred ''Om'' symbol, and the temple houses one of the twelve Jyotirlingas.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Pitambara Peeth', 'Maa Pitambara Peeth Datia',
  'Goddess Bagalamukhi & Dhumavati', ARRAY[]::TEXT[],
  'Devi',
  'Datia', 'Madhya Pradesh',
  'Datia, Madhya Pradesh 475661',
  '25.6700', '78.4600',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Important Tantric Shakti centre; visited by many political leaders for blessings',
  'October to March',
  ARRAY['Navaratri'],
  '+91-5813262035', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 11600,
  '475661', 'Datia Railway Station (3 km)', 'Gwalior Airport (75 km)',
  'A renowned centre of Tantric worship dedicated to the goddesses Bagalamukhi and Dhumavati, frequently visited by political and public figures seeking blessings.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Maa Sharda Devi Temple Maihar', 'Maihar Devi Temple',
  'Goddess Sharda (Saraswati)', ARRAY[]::TEXT[],
  'Devi',
  'Maihar', 'Madhya Pradesh',
  'Maihar, Satna District, Madhya Pradesh 485771',
  '24.2667', '80.7667',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Hilltop Shakti Peeth reached by over 1000 steps or ropeway',
  'October to March',
  ARRAY['Navaratri'],
  '+91-1147041253', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 13400,
  '485771', 'Maihar Railway Station (4 km)', 'Khajuraho Airport (95 km)',
  'One of the 51 Shakti Peethas, this temple sits atop the Trikuta hill and is reached by a flight of over 1,000 steps or a modern ropeway.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Birla Mandir Bhopal', 'Lakshmi Narayan Temple Bhopal',
  'Lord Vishnu & Goddess Lakshmi', ARRAY[]::TEXT[],
  'Vaishnava',
  'Bhopal', 'Madhya Pradesh',
  'Arera Hills, Bhopal, Madhya Pradesh 462011',
  '23.2380', '77.4030',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Modern hilltop temple with panoramic views of Bhopal city and Upper Lake',
  'October to March',
  ARRAY['Janmashtami','Diwali'],
  '+91-4384569797', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.4', 9800,
  '462011', 'Bhopal Junction (6 km)', 'Raja Bhoj Airport Bhopal (12 km)',
  'A relatively modern temple built by the Birla family atop Arera Hills, offering sweeping views over Bhopal city and its lakes.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Mahabodhi Temple', 'Bodh Gaya Mahabodhi Temple',
  'Lord Buddha', ARRAY[]::TEXT[],
  'Buddhist',
  'Bodh Gaya', 'Bihar',
  'Bodh Gaya, Gaya District, Bihar 824231',
  '24.6959', '84.9914',
  '5:00 AM - 9:00 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'UNESCO World Heritage Site marking Buddha''s enlightenment under the Bodhi Tree',
  'October to March',
  ARRAY['Buddha Purnima','Bodhi Day'],
  '+91-3619936505', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.8', 57200,
  '824231', 'Gaya Junction (13 km)', 'Gaya Airport (5 km)',
  'A UNESCO World Heritage Site marking the exact spot where Siddhartha Gautama is believed to have attained enlightenment under the Bodhi Tree over 2,500 years ago.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Vishnupad Temple', 'Vishnupad Mandir Gaya',
  'Lord Vishnu', ARRAY[]::TEXT[],
  'Vaishnava',
  'Gaya', 'Bihar',
  'Vishnupad, Gaya, Bihar 823001',
  '24.7833', '85.0000',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Houses a footprint impression of Lord Vishnu in solid rock; pind-daan rituals',
  'October to March',
  ARRAY['Pitru Paksha Mela'],
  '+91-6253260170', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 21300,
  '823001', 'Gaya Junction (2 km)', 'Gaya Airport (8 km)',
  'Built on the banks of the Falgu river, the temple''s sanctum houses a footprint believed to be that of Lord Vishnu, and is a major site for ancestral pind-daan rituals.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Takht Sri Patna Sahib', 'Patna Sahib Gurudwara',
  'Guru Gobind Singh', ARRAY[]::TEXT[],
  'Sikh',
  'Patna', 'Bihar',
  'Patna Sahib, Patna, Bihar 800008',
  '25.6177', '85.1486',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the five Takhts of Sikhism; birthplace of Guru Gobind Singh',
  'October to March',
  ARRAY['Prakash Utsav (Guru Gobind Singh Jayanti)'],
  '+91-6911710847', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.7', 19600,
  '800008', 'Patna Junction (4 km)', 'Jay Prakash Narayan Airport Patna (8 km)',
  'One of the five Takhts (seats of authority) of Sikhism, this gurudwara marks the birthplace of the tenth Sikh Guru, Guru Gobind Singh.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Kamakhya Temple', 'Kamakhya Devi Mandir',
  'Goddess Kamakhya (Shakti)', ARRAY[]::TEXT[],
  'Devi',
  'Guwahati', 'Assam',
  'Nilachal Hill, Guwahati, Assam 781010',
  '26.1664', '91.7050',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the most important Shakti Peethas; famous Ambubachi Mela menstruation festival',
  'October to March',
  ARRAY['Ambubachi Mela','Navaratri'],
  '+91-8596025752', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 38900,
  '781010', 'Kamakhya Railway Station (1 km)', 'Lokpriya Gopinath Bordoloi Airport (25 km)',
  'One of the oldest of the 51 Shakti Peethas and a major centre of Tantric worship, famous for the annual Ambubachi Mela which celebrates the goddess''s menstrual cycle.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Umananda Temple', 'Umananda Mandir',
  'Lord Shiva', ARRAY['Parvati'],
  'Shiva',
  'Guwahati', 'Assam',
  'Peacock Island, Brahmaputra River, Guwahati, Assam 781001',
  '26.1928', '91.7458',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Located on Peacock Island, claimed to be the smallest inhabited river island in the world',
  'October to March',
  ARRAY['Maha Shivratri (Doul Utsav)'],
  '+91-5779810030', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.4', 8900,
  '781001', 'Guwahati Railway Station (3 km)', 'Lokpriya Gopinath Bordoloi Airport (25 km)',
  'Situated on Peacock Island in the Brahmaputra, often cited as one of the smallest inhabited river islands in the world, reached by a short ferry ride.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Navagraha Temple Guwahati', 'Navagraha Mandir',
  'Nine Planetary Deities', ARRAY[]::TEXT[],
  'Navagraha',
  'Guwahati', 'Assam',
  'Chitrachal Hill, Guwahati, Assam 781001',
  '26.1850', '91.7600',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Hilltop temple dedicated to all nine celestial deities (Navagraha) under one roof',
  'October to March',
  ARRAY['Navagraha Puja days'],
  '+91-9153609133', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.3', 5400,
  '781001', 'Guwahati Railway Station (4 km)', 'Lokpriya Gopinath Bordoloi Airport (25 km)',
  'Set atop Chitrachal Hill, this temple houses nine shrines under a single dark dome dedicated to the nine planetary deities of Hindu astrology.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Durgiana Temple', 'Durgiana Mandir Amritsar',
  'Goddess Durga', ARRAY[]::TEXT[],
  'Devi',
  'Amritsar', 'Punjab',
  'Lawrence Road, Amritsar, Punjab 143001',
  '31.6260', '74.8717',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Built similar in style to the Golden Temple with a silver-plated gate and water tank',
  'October to March',
  ARRAY['Navaratri','Diwali'],
  '+91-3594672521', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 17300,
  '143001', 'Amritsar Junction (2 km)', 'Sri Guru Ram Dass Jee International Airport (10 km)',
  'Modelled architecturally on the Golden Temple, this Hindu temple features a similar water tank and a silver-plated entrance gate, dedicated to Goddess Durga and Lakshmi-Narayana.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Takht Sri Keshgarh Sahib', 'Anandpur Sahib Gurudwara',
  'Guru Gobind Singh', ARRAY[]::TEXT[],
  'Sikh',
  'Anandpur Sahib', 'Punjab',
  'Anandpur Sahib, Rupnagar District, Punjab 140118',
  '31.2333', '76.5000',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Birthplace of the Khalsa, founded by Guru Gobind Singh in 1699',
  'October to March',
  ARRAY['Hola Mohalla','Baisakhi'],
  '+91-9374981280', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 26400,
  '140118', 'Anandpur Sahib Railway Station (1 km)', 'Sri Guru Ram Dass Jee International Airport (90 km)',
  'One of the five Takhts of Sikhism, marking the site where Guru Gobind Singh founded the Khalsa Panth in 1699.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Bhagwan Valmiki Tirath Sthal', 'Valmiki Ashram Amritsar',
  'Sage Valmiki', ARRAY[]::TEXT[],
  'Ashram',
  'Amritsar', 'Punjab',
  'Ramtirath, Amritsar, Punjab 143001',
  '31.5500', '74.7833',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Believed to be the ashram of Sage Valmiki where Sita took refuge and Luv-Kush were born',
  'October to March',
  ARRAY['Ram Navami','Valmiki Jayanti'],
  '+91-4113018435', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.3', 4700,
  '143001', 'Amritsar Junction (12 km)', 'Sri Guru Ram Dass Jee International Airport (5 km)',
  'According to tradition, this site was the hermitage of Sage Valmiki, where Sita lived during her exile and gave birth to Lava and Kusha.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Chintpurni Temple', 'Maa Chintpurni Mandir',
  'Goddess Chintpurni (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Una', 'Himachal Pradesh',
  'Chintpurni, Una District, Himachal Pradesh 177110',
  '31.7833', '76.1167',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the 51 Shakti Peethas, set amid the Shivalik hills',
  'October to March',
  ARRAY['Navaratri'],
  '+91-8681105726', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 13600,
  '177110', 'Una Himachal Railway Station (25 km)', 'Gaggal Airport Kangra (60 km)',
  'One of the Shakti Peethas of the Himalayas, this temple draws huge crowds especially during Navratri, set amid the scenic Shivalik foothills.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Naina Devi Temple', 'Shri Naina Devi Ji',
  'Goddess Naina Devi (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Bilaspur', 'Himachal Pradesh',
  'Naina Devi, Bilaspur District, Himachal Pradesh 174031',
  '31.2667', '76.5500',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Shakti Peeth overlooking the Gobind Sagar reservoir; reached by ropeway',
  'October to March',
  ARRAY['Navaratri'],
  '+91-1322985625', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 15800,
  '174031', 'Anandpur Sahib Railway Station (35 km)', 'Gaggal Airport Kangra (90 km)',
  'One of the 51 Shakti Peethas, perched on a hill overlooking the Gobind Sagar reservoir formed by the Bhakra Dam, accessible by ropeway from the base.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Baijnath Temple', 'Baijnath Shiva Temple',
  'Lord Shiva (Vaidyanath)', ARRAY[]::TEXT[],
  'Shiva',
  'Kangra', 'Himachal Pradesh',
  'Baijnath, Kangra District, Himachal Pradesh 176125',
  '32.0500', '76.6500',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  '12th-century Nagara-style stone temple dedicated to Shiva as the divine physician',
  'October to March',
  ARRAY['Maha Shivratri'],
  '+91-8190607071', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 9100,
  '176125', 'Baijnath Paprola Railway Station (1 km)', 'Gaggal Airport Kangra (20 km)',
  'An ancient 12th-century stone temple dedicated to Shiva as Vaidyanath (lord of physicians), considered one of the finest examples of early hill-temple architecture.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Bhimakali Temple', 'Bhimakali Mandir Sarahan',
  'Goddess Bhimakali (Kali)', ARRAY[]::TEXT[],
  'Devi',
  'Sarahan', 'Himachal Pradesh',
  'Sarahan, Shimla District, Himachal Pradesh 172033',
  '31.5167', '77.8167',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Unique blend of Hindu and Buddhist hill architecture; former royal temple of Bushahr kingdom',
  'October to March',
  ARRAY['Navaratri'],
  '+91-8371822927', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 8400,
  '172033', 'Shimla Railway Station (180 km)', 'Shimla Airport (185 km)',
  'Combining Hindu and Buddhist architectural styles typical of the Himalayan hill states, this temple was the seat of the royal family of the former Bushahr kingdom.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Yadagirigutta Lakshmi Narasimha Temple', 'Yadadri Temple',
  'Lord Narasimha (Vishnu)', ARRAY['Goddess Lakshmi'],
  'Vaishnava',
  'Yadagirigutta', 'Telangana',
  'Yadagirigutta, Yadadri Bhuvanagiri District, Telangana 508115',
  '17.5833', '78.9500',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Recently renovated grand hilltop temple complex; cave shrine of self-manifested Narasimha',
  'October to March',
  ARRAY['Brahmotsavam','Narasimha Jayanti'],
  '+91-8895923167', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 31900,
  '508115', 'Yadagirigutta Railway Station (1 km)', 'Rajiv Gandhi International Airport Hyderabad (75 km)',
  'Recently renovated into a grand temple complex, the cave shrine here is believed to house a self-manifested (Swayambhu) form of Lord Narasimha.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Bhadrachalam Temple', 'Sri Sita Ramachandraswamy Temple',
  'Lord Rama', ARRAY['Sita','Lakshman'],
  'Vaishnava',
  'Bhadrachalam', 'Telangana',
  'Bhadrachalam, Bhadradri Kothagudem District, Telangana 507111',
  '17.6667', '80.7833',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'On the banks of the Godavari; associated with poet-devotee Bhakta Ramadas',
  'October to March',
  ARRAY['Sita Rama Kalyanam (Ram Navami)'],
  '+91-2228136209', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 27600,
  '507111', 'Bhadrachalam Road Railway Station (40 km)', 'Rajiv Gandhi International Airport Hyderabad (300 km)',
  'Located on the banks of the Godavari river, this temple is closely associated with Bhakta Ramadas, a 17th-century devotee-poet who was imprisoned for using temple funds to build it.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Ramappa Temple', 'Rudreshwara Temple',
  'Lord Shiva (Ramalingeswara)', ARRAY[]::TEXT[],
  'Shiva',
  'Warangal', 'Telangana',
  'Palampet, Mulugu District, Telangana 506166',
  '18.2667', '79.9500',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'UNESCO World Heritage Site known for floating bricks and intricate Kakatiya sculpture',
  'October to March',
  ARRAY['Maha Shivratri'],
  '+91-9599114674', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.7', 14200,
  '506166', 'Warangal Railway Station (70 km)', 'Rajiv Gandhi International Airport Hyderabad (210 km)',
  'A UNESCO World Heritage Site built during the Kakatiya dynasty in the 13th century, famous for its lightweight ''floating'' bricks and exquisite sculptural carvings.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Birla Mandir Hyderabad', 'Lakshmi Narayan Temple Hyderabad',
  'Lord Vishnu & Goddess Lakshmi', ARRAY[]::TEXT[],
  'Vaishnava',
  'Hyderabad', 'Telangana',
  'Naubath Pahad, Hyderabad, Telangana 500028',
  '17.4062', '78.4691',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'White marble hilltop temple overlooking Hussain Sagar lake',
  'October to March',
  ARRAY['Janmashtami','Diwali'],
  '+91-7356795723', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 21700,
  '500028', 'Hyderabad Deccan (5 km)', 'Rajiv Gandhi International Airport (35 km)',
  'Built entirely of white Rajasthani marble atop Naubath Pahad hill, this temple offers panoramic views of Hyderabad and the Hussain Sagar lake.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Shanta Durga Temple', 'Shantadurga Temple Kavalem',
  'Goddess Shantadurga (Durga)', ARRAY[]::TEXT[],
  'Devi',
  'Ponda', 'Goa',
  'Kavalem, Ponda Taluk, Goa 403115',
  '15.4167', '74.0833',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Largest and most important Hindu temple in Goa; distinct Goan-Portuguese architectural fusion',
  'October to March',
  ARRAY['Zatra (temple festival)','Navaratri'],
  '+91-1063754540', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 18600,
  '403115', 'Madgaon Railway Station (25 km)', 'Goa International Airport (28 km)',
  'The largest and most revered Hindu temple in Goa, showcasing a distinctive fusion of traditional Hindu and Portuguese-colonial architectural styles.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Shri Manguesh Temple', 'Mangueshi Temple',
  'Lord Shiva (Manguesh)', ARRAY[]::TEXT[],
  'Shiva',
  'Ponda', 'Goa',
  'Mangeshi, Ponda Taluk, Goa 403104',
  '15.4500', '73.9667',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'One of the most visited and largest temples in Goa with a distinctive seven-storeyed deepastambha',
  'October to March',
  ARRAY['Jatra Utsav','Maha Shivratri'],
  '+91-4046765577', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.6', 16400,
  '403104', 'Madgaon Railway Station (22 km)', 'Goa International Airport (25 km)',
  'One of the most frequented temples in Goa, recognisable by its seven-storeyed lamp tower (deepastambha) and blend of Hindu and European architectural elements.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Mookambika Temple Kollur', 'Sri Mookambika Temple',
  'Goddess Mookambika (Durga/Saraswati)', ARRAY[]::TEXT[],
  'Devi',
  'Kollur', 'Karnataka',
  'Kollur, Udupi District, Karnataka 576220',
  '13.8667', '74.8167',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Combines worship of Shakti and Jyotirlinga in the Western Ghats; popular Vidyarambham ceremonies',
  'October to March',
  ARRAY['Navaratri','Chaturmasya'],
  '+91-4245441872', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'FEATURED', '4.7', 19300,
  '576220', 'Byndoor Railway Station (25 km)', 'Mangalore International Airport (135 km)',
  'Nestled in the Western Ghats, the temple is unique for combining the worship of the goddess Mookambika with a Jyotirlinga, and is popular for Vidyarambham (initiation into learning) ceremonies for children.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Ganpatipule Temple', 'Paschim Dwar Ganapati Temple',
  'Lord Ganesha', ARRAY[]::TEXT[],
  'Other',
  'Ratnagiri', 'Maharashtra',
  'Ganpatipule, Ratnagiri District, Maharashtra 415616',
  '17.1444', '73.2667',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Self-manifested Ganesha idol facing west on a scenic Konkan beach',
  'October to March',
  ARRAY['Ganesh Chaturthi','Maha Shivratri'],
  '+91-3501290170', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 12900,
  '415616', 'Ratnagiri Railway Station (25 km)', 'Pune Airport (330 km)',
  'One of the eight important Ganesha shrines (Ashtavinayaka-equivalent) on the Konkan coast, the swayambhu (self-manifested) idol uniquely faces west towards the Arabian Sea.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Kalka Mata Temple Pathankot', 'Mukteshwar Mahadev Temple',
  'Lord Shiva', ARRAY['Goddess Kalka'],
  'Shiva',
  'Pathankot', 'Punjab',
  'Mukerian Road, Pathankot, Punjab 145001',
  '32.2746', '75.6521',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Ancient hill temple complex on the banks of a stream amid pine forests',
  'October to March',
  ARRAY['Maha Shivratri','Navaratri'],
  '+91-3073236576', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.3', 4100,
  '145001', 'Pathankot Junction (3 km)', 'Gaggal Airport Kangra (45 km)',
  'An ancient temple complex set amid pine forests on the banks of a stream, popular with pilgrims travelling between Punjab and the Himachal shrines.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Bhrigu Lake Temple Region - Markandeshwar', 'Markandeshwar Mahadev Temple',
  'Lord Shiva', ARRAY[]::TEXT[],
  'Shiva',
  'Sirmaur', 'Himachal Pradesh',
  'Markanda, Sirmaur District, Himachal Pradesh 173025',
  '30.5667', '77.2833',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Ancient cave temple associated with sage Markandeya on the Markanda river',
  'October to March',
  ARRAY['Maha Shivratri'],
  '+91-8315155984', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.3', 3600,
  '173025', 'Kalka Railway Station (60 km)', 'Shimla Airport (90 km)',
  'An ancient cave shrine on the banks of the Markanda river, associated with the sage Markandeya who is said to have meditated here.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
),
(
  'Triveni Sangam Akshayavat Temple', 'Akshayavat Prayagraj',
  'Lord Vishnu', ARRAY['Akshayavat tree'],
  'Vaishnava',
  'Prayagraj', 'Uttar Pradesh',
  'Sangam Area, Prayagraj, Uttar Pradesh 211003',
  '25.4310', '81.8836',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM', '6:00 AM', '7:00 PM',
  'Free (special darshan tickets available)', 'Modest traditional attire recommended; avoid shorts and sleeveless tops',
  'Sacred fig tree shrine at the confluence of Ganga, Yamuna and Saraswati rivers; Kumbh Mela site',
  'October to March',
  ARRAY['Kumbh Mela','Magh Mela'],
  '+91-2669420129', 'https://www.templepurohit.com',
  '/src/assets/images/hero-temple.jpg',
  'POPULAR', '4.5', 16700,
  '211003', 'Prayagraj Junction (5 km)', 'Prayagraj Airport (15 km)',
  'Located within the Allahabad Fort near the Triveni Sangam, this shrine houses the legendary immortal banyan tree (Akshayavat) and is a key site during the Kumbh Mela.',
  'Special darshan available on festival days; check temple notice board for VIP/Sevā passes',
  'Open all days'
)
ON CONFLICT (name, location_city) DO UPDATE SET
    alternate_name        = EXCLUDED.alternate_name,
    deity                 = EXCLUDED.deity,
    other_deities         = EXCLUDED.other_deities,
    category              = EXCLUDED.category,
    location_state        = EXCLUDED.location_state,
    full_address          = EXCLUDED.full_address,
    latitude              = EXCLUDED.latitude,
    longitude             = EXCLUDED.longitude,
    timings_general       = EXCLUDED.timings_general,
    timings_morning_aarti = EXCLUDED.timings_morning_aarti,
    timings_evening_aarti = EXCLUDED.timings_evening_aarti,
    entry_fee             = EXCLUDED.entry_fee,
    dress_code            = EXCLUDED.dress_code,
    famous_for            = EXCLUDED.famous_for,
    best_time_visit       = EXCLUDED.best_time_visit,
    festivals             = EXCLUDED.festivals,
    contact_phone         = EXCLUDED.contact_phone,
    website               = EXCLUDED.website,
    image_url             = EXCLUDED.image_url,
    tag                   = EXCLUDED.tag,
    rating                = EXCLUDED.rating,
    reviews               = EXCLUDED.reviews,
    pincode               = EXCLUDED.pincode,
    nearest_railway       = EXCLUDED.nearest_railway,
    nearest_airport       = EXCLUDED.nearest_airport,
    history               = EXCLUDED.history,
    special_darshan       = EXCLUDED.special_darshan,
    timings_closed_on     = EXCLUDED.timings_closed_on;