/**
 * seedTemples.js
 *
 * Strategy:
 *   1. Try to parse a Kaggle CSV if present at ./data/temples.csv
 *      (download from https://www.kaggle.com/datasets/... and place it there)
 *   2. If the CSV is absent / parse fails, fall back to the 50+ hardcoded
 *      famous Indian temples below so the app always has data.
 *
 * Run:  node src/scripts/seedTemples.js
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const pool = require('../config/db');
const { parse } = require('csv-parse/sync');

// ─────────────────────────────────────────────────────────────────────────────
// HARDCODED SEED DATA (used when no Kaggle CSV is present)
// ─────────────────────────────────────────────────────────────────────────────
const HARDCODED_TEMPLES = [
  {
    name: 'Kashi Vishwanath Temple',
    alternate_name: 'Golden Temple of Varanasi',
    deity: 'Lord Shiva',
    other_deities: ['Goddess Annapurna', 'Goddess Saraswati'],
    category: 'Shiva',
    location_city: 'Varanasi',
    location_state: 'Uttar Pradesh',
    full_address: 'Lahori Tola, Varanasi, Uttar Pradesh 221001',
    pincode: '221001',
    latitude: 25.3109,
    longitude: 83.0107,
    nearest_railway: 'Varanasi Junction (2 km)',
    nearest_airport: 'Lal Bahadur Shastri International Airport (25 km)',
    timings_general: '3:00 AM – 11:00 PM',
    timings_morning_aarti: '3:00 AM',
    timings_evening_aarti: '7:00 PM',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free',
    dress_code: 'Traditional Indian attire preferred, no shorts',
    special_darshan: 'VIP darshan tickets available at ₹300',
    famous_for: 'One of the 12 Jyotirlingas; one of the holiest Hindu pilgrimage sites; mentioned in the Skanda Purana.',
    history: 'The original temple was demolished in 1669 by Aurangzeb and the current structure was built by Maratha ruler Ahilyabai Holkar in 1780. The gold-plated shikhara was donated by Maharaja Ranjit Singh.',
    best_time_visit: 'October to March (winter months). Avoid May-June peak summer.',
    festivals: ['Mahashivaratri', 'Dev Deepawali', 'Karthik Purnima', 'Nag Panchami'],
    contact_phone: '+91-542-2392278',
    website: 'https://shrikashivishwanath.org',
    image_url: '/src/assets/images/temple-kashi.jpg',
    tag: 'LIVE',
    rating: 4.9,
    reviews: 32410,
  },
  {
    name: 'Meenakshi Amman Temple',
    alternate_name: 'Meenakshi Sundareswarar Temple',
    deity: 'Goddess Meenakshi',
    other_deities: ['Lord Sundareswarar (Shiva)', 'Lord Ganesha', 'Lord Murugan'],
    category: 'Devi',
    location_city: 'Madurai',
    location_state: 'Tamil Nadu',
    full_address: 'Madurai Main, Madurai, Tamil Nadu 625001',
    pincode: '625001',
    latitude: 9.9195,
    longitude: 78.1193,
    nearest_railway: 'Madurai Junction (1.5 km)',
    nearest_airport: 'Madurai Airport (12 km)',
    timings_general: '5:00 AM – 12:30 PM, 4:00 PM – 9:30 PM',
    timings_morning_aarti: '5:00 AM',
    timings_evening_aarti: '6:30 PM',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free (camera fee ₹50)',
    dress_code: 'Traditional attire mandatory; no shorts or sleeveless tops',
    special_darshan: 'Special darshan at ₹100 and ₹200',
    famous_for: 'One of the largest temple complexes in India; known for its 14 majestic gopurams; a UNESCO World Heritage candidate.',
    history: 'The original temple is believed to be over 2,500 years old; extensively renovated by Nayak rulers in the 16th-17th century; the 14 gopurams contain over 33,000 sculptures.',
    best_time_visit: 'October to March. Chithirai festival in April-May is spectacular.',
    festivals: ['Chithirai Festival', 'Aadi Pooram', 'Navratri', 'Karthigai Deepam'],
    contact_phone: '+91-452-2346760',
    website: 'https://maduraimeenakshiammantemple.hrce.tn.gov.in',
    image_url: '/src/assets/images/temple-meenakshi.jpg',
    tag: 'POPULAR',
    rating: 4.8,
    reviews: 28700,
  },
  {
    name: 'Tirupati Balaji Temple',
    alternate_name: 'Sri Venkateswara Temple, Tirumala',
    deity: 'Lord Venkateswara',
    other_deities: ['Goddess Padmavathi', 'Goddess Alarmel Mangai'],
    category: 'Vishnu',
    location_city: 'Tirupati',
    location_state: 'Andhra Pradesh',
    full_address: 'Tirumala, Tirupati, Andhra Pradesh 517504',
    pincode: '517504',
    latitude: 13.6833,
    longitude: 79.3500,
    nearest_railway: 'Tirupati Railway Station (23 km)',
    nearest_airport: 'Tirupati Airport (14 km from Tirupati)',
    timings_general: '2:30 AM – 1:30 AM (next day)',
    timings_morning_aarti: '3:00 AM (Thiruvanandal)',
    timings_evening_aarti: '8:30 PM (Ekanta Seva)',
    timings_closed_on: 'Open all days',
    entry_fee: '₹300 for Sarva Darshan, VIP Darshan ₹3000',
    dress_code: 'Dhoti/saree for men/women; no jeans, short pants, or revealing clothes',
    special_darshan: 'SSD (Srivari Seva Darshan) ₹1500; Arjitha Seva tickets available online via TTD website',
    famous_for: 'The richest and most visited temple in the world; receives over 50,000 pilgrims daily; Lord Venkateswara is considered the presiding deity of the Kali Yuga.',
    history: 'The temple is believed to be over 1,000 years old; the current structure was built primarily during the Vijayanagara Empire. The Tirumala Tirupati Devasthanams (TTD) manages the temple and its vast endowments.',
    best_time_visit: 'September to February. Brahmotsavam in September is the grand annual festival.',
    festivals: ['Brahmotsavam', 'Vaikunta Ekadasi', 'Kalyanotsavam', 'Rathasaptami'],
    contact_phone: '1800-425-4141 (TTD Toll Free)',
    website: 'https://www.tirumala.org',
    image_url: '/src/assets/images/temple-tirupati.jpg',
    tag: 'FEATURED',
    rating: 4.9,
    reviews: 54200,
  },
  {
    name: 'Somnath Temple',
    alternate_name: 'Deo Pattan',
    deity: 'Lord Shiva',
    other_deities: ['Goddess Parvati', 'Lord Ganesha'],
    category: 'Shiva',
    location_city: 'Veraval',
    location_state: 'Gujarat',
    full_address: 'Prabhas Patan, Veraval, Gir Somnath, Gujarat 362268',
    pincode: '362268',
    latitude: 20.8880,
    longitude: 70.4015,
    nearest_railway: 'Veraval Railway Station (7 km)',
    nearest_airport: 'Diu Airport (66 km)',
    timings_general: '6:00 AM – 9:30 PM',
    timings_morning_aarti: '7:00 AM',
    timings_evening_aarti: '7:00 PM',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free',
    dress_code: 'Modest attire; no shorts',
    special_darshan: 'Aarti passes available at the temple counter',
    famous_for: 'First among the 12 Jyotirlingas; repeatedly destroyed and rebuilt; stands on the shore of the Arabian Sea; Sound and Light show in the evening.',
    history: 'The temple has been destroyed and reconstructed at least six times throughout history, most famously by Mahmud of Ghazni in 1025 CE. The current temple was reconstructed in 1951 under the leadership of Sardar Vallabhbhai Patel.',
    best_time_visit: 'October to March. Shivratri and Kartik Purnima are major festival dates.',
    festivals: ['Mahashivaratri', 'Kartik Purnima', 'Somnath Fair'],
    contact_phone: '+91-2876-231254',
    website: 'https://somnath.org',
    image_url: '/src/assets/images/temple-somnath.jpg',
    tag: 'LIVE',
    rating: 4.8,
    reviews: 19800,
  },
  {
    name: 'Kedarnath Temple',
    deity: 'Lord Shiva',
    other_deities: ['Goddess Parvati', 'Adi Shankaracharya Samadhi'],
    category: 'Shiva',
    location_city: 'Kedarnath',
    location_state: 'Uttarakhand',
    full_address: 'Kedarnath, Rudraprayag District, Uttarakhand 246445',
    pincode: '246445',
    latitude: 30.7346,
    longitude: 79.0669,
    nearest_railway: 'Rishikesh Railway Station (216 km)',
    nearest_airport: 'Jolly Grant Airport, Dehradun (238 km)',
    timings_general: '6:00 AM – 7:00 PM (May to November only)',
    timings_morning_aarti: '6:00 AM',
    timings_evening_aarti: '7:00 PM',
    timings_closed_on: 'Closed November to April (winter)',
    entry_fee: 'Free',
    dress_code: 'Traditional attire recommended; carry warm clothes',
    special_darshan: 'VIP darshan via Badrinath Kedarnath Temples Committee',
    famous_for: 'One of the 12 Jyotirlingas; situated at 3,583 m altitude in the Himalayas; part of the Char Dham Yatra pilgrimage.',
    history: 'The temple is believed to have been constructed by the Pandavas and restored by Adi Shankaracharya in the 8th century. It survived the devastating 2013 floods with minimal structural damage.',
    best_time_visit: 'May to June and September to October (temple open season). Avoid July-August monsoon.',
    festivals: ['Mahashivaratri', 'Kedarnath Opening Ceremony (May)', 'Deepawali'],
    contact_phone: '+91-1364-263536',
    website: 'https://badrinath-kedarnath.gov.in',
    image_url: '/src/assets/images/temple-kashi.jpg',
    tag: 'LIVE',
    rating: 4.9,
    reviews: 23400,
  },
  {
    name: 'Vaishno Devi Temple',
    deity: 'Mata Vaishno Devi',
    other_deities: ['Mata Saraswati', 'Mata Lakshmi', 'Mata Kali'],
    category: 'Devi',
    location_city: 'Katra',
    location_state: 'Jammu & Kashmir',
    full_address: 'Trikuta Hills, Katra, Reasi District, J&K 182301',
    pincode: '182301',
    latitude: 33.0278,
    longitude: 74.9519,
    nearest_railway: 'Katra Railway Station (2 km)',
    nearest_airport: 'Jammu Airport (50 km)',
    timings_general: 'Open 24 Hours (trek available)',
    timings_morning_aarti: '4:00 AM',
    timings_evening_aarti: '8:00 PM',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free (Yatra Parchi registration ₹0-50)',
    dress_code: 'Traditional attire preferred; comfortable trekking shoes required',
    special_darshan: 'Online registration at SANJICHHAT and helicopter services available',
    famous_for: 'One of the most visited pilgrimage sites in India with over 8 million visitors annually; cave shrine in Trikuta Hills; three natural rock formations representing the goddess.',
    history: 'The cave shrine is believed to be thousands of years old; officially managed by the Shri Mata Vaishno Devi Shrine Board since 1986. The shrine became very popular in the 1970s when Pandit Premnath Dogra promoted pilgrimage.',
    best_time_visit: 'March to October. Navratri (April & October) sees peak pilgrimage.',
    festivals: ['Navratri (Chaitra)', 'Navratri (Sharad)', 'Dussehra'],
    contact_phone: '01991-234804',
    website: 'https://maavaishnodevi.org',
    image_url: '/src/assets/images/temple-meenakshi.jpg',
    tag: 'POPULAR',
    rating: 4.9,
    reviews: 61000,
  },
  {
    name: 'Jagannath Temple',
    alternate_name: 'Shri Jagannath Puri Temple',
    deity: 'Lord Jagannath',
    other_deities: ['Balabhadra', 'Subhadra', 'Sudarshana'],
    category: 'Vishnu',
    location_city: 'Puri',
    location_state: 'Odisha',
    full_address: 'Grand Road, Puri, Odisha 752001',
    pincode: '752001',
    latitude: 19.8046,
    longitude: 85.8179,
    nearest_railway: 'Puri Railway Station (2 km)',
    nearest_airport: 'Biju Patnaik International Airport, Bhubaneswar (60 km)',
    timings_general: '5:00 AM – 11:00 PM',
    timings_morning_aarti: '5:00 AM (Mangal Alati)',
    timings_evening_aarti: '8:00 PM (Sandhya Dhoop)',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free (Hindus only; non-Hindus not permitted inside)',
    dress_code: 'Traditional attire; no leather items allowed inside',
    special_darshan: 'Srimandir Heritage Corridor permits available; Mailam Darshan available',
    famous_for: 'One of the Char Dham pilgrimage sites; world-famous Rath Yatra chariot festival; the wooden idols are replaced every 12-19 years in a secret Nabakalebara ceremony.',
    history: 'The current structure was built by King Anantavarman Chodaganga Deva in the 12th century. The Rath Yatra festival has been continuously held for over 2,000 years and is the world\'s largest chariot procession.',
    best_time_visit: 'October to February. Rath Yatra (June/July) is iconic but extremely crowded.',
    festivals: ['Rath Yatra', 'Bahuda Yatra', 'Snana Yatra', 'Chandan Yatra'],
    contact_phone: '+91-6752-222002',
    website: 'https://www.shreejagannath.nic.in',
    image_url: '/src/assets/images/temple-tirupati.jpg',
    tag: 'POPULAR',
    rating: 4.7,
    reviews: 32000,
  },
  {
    name: 'Harmandir Sahib',
    alternate_name: 'Golden Temple',
    deity: 'Sri Guru Granth Sahib',
    other_deities: [],
    category: 'Other',
    location_city: 'Amritsar',
    location_state: 'Punjab',
    full_address: 'Golden Temple Rd, Atta Mandi, Katra Ahluwalia, Amritsar, Punjab 143006',
    pincode: '143006',
    latitude: 31.6200,
    longitude: 74.8765,
    nearest_railway: 'Amritsar Railway Station (2 km)',
    nearest_airport: 'Sri Guru Ram Dass Jee International Airport (11 km)',
    timings_general: 'Open 24 Hours',
    timings_morning_aarti: '4:00 AM (Asa di Var)',
    timings_evening_aarti: '9:30 PM (Kirtan Sohila)',
    timings_closed_on: 'Open all days',
    entry_fee: 'Completely Free (langar free for all)',
    dress_code: 'Head must be covered; shoes removed; no smoking or alcohol',
    special_darshan: 'No ticket system; all welcome 24 hours',
    famous_for: 'The holiest shrine in Sikhism; upper floors clad in 500 kg of pure gold; feeds 100,000 people free daily in the langar (community kitchen); symbol of unity and brotherhood.',
    history: 'Founded by Guru Arjan Dev Ji in 1604; the current marble and gold structure dates from the early 19th century during Maharaja Ranjit Singh\'s reign. The temple was attacked and damaged in 1984 but restored.',
    best_time_visit: 'October to March. Guru Nanak Jayanti and Baisakhi are magnificent festivals.',
    festivals: ['Guru Nanak Jayanti', 'Baisakhi', 'Diwali', 'Hola Mohalla'],
    contact_phone: '+91-183-2553957',
    website: 'https://www.sgpc.net',
    image_url: '/src/assets/images/temple-somnath.jpg',
    tag: 'FEATURED',
    rating: 5.0,
    reviews: 98700,
  },
  {
    name: 'Brihadeeswara Temple',
    alternate_name: 'Brihadeeswarar / Big Temple',
    deity: 'Lord Shiva',
    other_deities: ['Nandi', 'Goddess Periyānāyaki'],
    category: 'Shiva',
    location_city: 'Thanjavur',
    location_state: 'Tamil Nadu',
    full_address: 'Membalam Rd, Balaganapathy Nagar, Thanjavur, Tamil Nadu 613009',
    pincode: '613009',
    latitude: 10.7827,
    longitude: 79.1317,
    nearest_railway: 'Thanjavur Junction (2 km)',
    nearest_airport: 'Tiruchirappalli International Airport (56 km)',
    timings_general: '6:00 AM – 12:30 PM, 4:00 PM – 8:30 PM',
    timings_morning_aarti: '6:00 AM',
    timings_evening_aarti: '6:00 PM',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free',
    dress_code: 'Modest attire; no shorts',
    special_darshan: null,
    famous_for: 'UNESCO World Heritage Site; one of the greatest examples of Chola architecture; the 66-metre vimana casts no shadow at noon; the shikhara capstone weighs 80 tonnes.',
    history: 'Built by the Chola king Raja Raja I between 1003–1010 CE. The temple is 1,000 years old and one of the finest examples of Dravidian architecture in the world.',
    best_time_visit: 'November to February. Theppotsavam boat festival (March) is beautiful.',
    festivals: ['Mahashivaratri', 'Theppotsavam', 'Karthigai Deepam'],
    contact_phone: '+91-4362-274505',
    website: null,
    image_url: '/src/assets/images/temple-kashi.jpg',
    tag: 'FEATURED',
    rating: 4.8,
    reviews: 15600,
  },
  {
    name: 'Badrinath Temple',
    alternate_name: 'Badrinath Dham',
    deity: 'Lord Vishnu (Badrinārāyaṇa)',
    other_deities: ['Kubera', 'Narada', 'Garuda'],
    category: 'Vishnu',
    location_city: 'Badrinath',
    location_state: 'Uttarakhand',
    full_address: 'Badrinath, Chamoli District, Uttarakhand 246422',
    pincode: '246422',
    latitude: 30.7433,
    longitude: 79.4938,
    nearest_railway: 'Rishikesh Railway Station (295 km)',
    nearest_airport: 'Jolly Grant Airport, Dehradun (314 km)',
    timings_general: '4:30 AM – 9:00 PM (May to November)',
    timings_morning_aarti: '4:30 AM (Mahabhishek)',
    timings_evening_aarti: '8:00 PM (Shayan Aarti)',
    timings_closed_on: 'Closed November to April (winter)',
    entry_fee: 'Free',
    dress_code: 'Traditional Indian attire; comfortable mountain clothing',
    special_darshan: 'Abhishek puja available; online booking through BKTC',
    famous_for: 'One of the Char Dhams; situated at 3,133 m altitude by the Alaknanda river; one of the 108 Divya Desams of Lord Vishnu.',
    history: 'The temple is believed to have been established by Adi Shankaracharya in the 8th century CE. The current structure dates from the 16th century and has been repaired multiple times after natural disasters.',
    best_time_visit: 'May to June and September to October. Avoid monsoon (July-August).',
    festivals: ['Badri Kedar Festival', 'Mata Murti Ka Mela', 'Devuthani Ekadashi'],
    contact_phone: '01389-222308',
    website: 'https://badrinath-kedarnath.gov.in',
    image_url: '/src/assets/images/temple-tirupati.jpg',
    tag: 'POPULAR',
    rating: 4.9,
    reviews: 19200,
  },
  {
    name: 'Siddhivinayak Temple',
    alternate_name: 'Shri Siddhivinayak Ganapati Mandir',
    deity: 'Lord Ganesha',
    other_deities: [],
    category: 'Other',
    location_city: 'Mumbai',
    location_state: 'Maharashtra',
    full_address: 'SK Bole Marg, Prabhadevi, Mumbai, Maharashtra 400028',
    pincode: '400028',
    latitude: 19.0176,
    longitude: 72.8302,
    nearest_railway: 'Dadar Railway Station (1 km)',
    nearest_airport: 'Chhatrapati Shivaji Maharaj International Airport (8 km)',
    timings_general: '5:30 AM – 10:00 PM',
    timings_morning_aarti: '5:30 AM',
    timings_evening_aarti: '8:30 PM',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free',
    dress_code: 'Modest attire; traditional preferred on festival days',
    special_darshan: 'VIP darshan available; online booking at siddhivinayak.org',
    famous_for: 'The most visited Ganesh temple in Mumbai; celebrities and politicians visit regularly; the Navratri and Ganesh Chaturthi celebrations are spectacular.',
    history: 'Built in 1801 by Deubai Patil. The temple underwent major renovation in 1990 and the current golden dome structure with marble facade was completed.',
    best_time_visit: 'Year-round. Ganesh Chaturthi (Aug/Sep) is extraordinary but crowded.',
    festivals: ['Ganesh Chaturthi', 'Angarki Chaturthi', 'Navratri'],
    contact_phone: '+91-22-24371606',
    website: 'https://siddhivinayak.org',
    image_url: '/src/assets/images/temple-somnath.jpg',
    tag: 'POPULAR',
    rating: 4.7,
    reviews: 41200,
  },
  {
    name: 'Ramanathaswamy Temple',
    alternate_name: 'Rameswaram Temple',
    deity: 'Lord Shiva (Ramanathaswamy)',
    other_deities: ['Goddess Parvathavarthini', 'Lord Vishnu', 'Lord Brahma'],
    category: 'Shiva',
    location_city: 'Rameswaram',
    location_state: 'Tamil Nadu',
    full_address: 'Rameswaram, Ramanathapuram District, Tamil Nadu 623526',
    pincode: '623526',
    latitude: 9.2882,
    longitude: 79.3175,
    nearest_railway: 'Rameswaram Railway Station (0.5 km)',
    nearest_airport: 'Madurai Airport (163 km)',
    timings_general: '5:00 AM – 1:00 PM, 3:00 PM – 9:00 PM',
    timings_morning_aarti: '5:00 AM',
    timings_evening_aarti: '7:00 PM',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free (puja charges apply)',
    dress_code: 'Traditional attire; men must remove shirt for darshan in main sanctum',
    special_darshan: '22 sacred theerthas (wells) bathing ritual',
    famous_for: 'One of the Char Dhams and one of the 12 Jyotirlingas; has the longest temple corridor in India at 1,200 metres; bathing in 22 sacred wells is considered highly auspicious.',
    history: 'Associated with the Ramayana; Lord Rama is believed to have worshipped Lord Shiva here. The present temple was built over several centuries with the Nayak rulers contributing most in the 16th-17th century.',
    best_time_visit: 'October to April. Maha Shivaratri and Brahmotsavam are the main festivals.',
    festivals: ['Mahashivaratri', 'Brahmotsavam', 'Thirukalyanam'],
    contact_phone: '+91-4573-221223',
    website: null,
    image_url: '/src/assets/images/temple-meenakshi.jpg',
    tag: 'FEATURED',
    rating: 4.8,
    reviews: 24500,
  },
  {
    name: 'Dwarkadheesh Temple',
    alternate_name: 'Jagat Mandir Dwarka',
    deity: 'Lord Krishna (Dwarkadheesh)',
    other_deities: ['Rukmini Devi', 'Devaki Mata'],
    category: 'Vishnu',
    location_city: 'Dwarka',
    location_state: 'Gujarat',
    full_address: 'Temple Rd, Dwarka, Gujarat 361335',
    pincode: '361335',
    latitude: 22.2378,
    longitude: 68.9677,
    nearest_railway: 'Dwarka Railway Station (2 km)',
    nearest_airport: 'Jamnagar Airport (137 km)',
    timings_general: '6:30 AM – 1:00 PM, 5:00 PM – 9:30 PM',
    timings_morning_aarti: '6:30 AM',
    timings_evening_aarti: '7:30 PM',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free',
    dress_code: 'Traditional attire; men must wear dhoti or kurta-pajama',
    special_darshan: 'Special puja arrangements available at temple counter',
    famous_for: 'One of the Char Dhams and Sapta Puri (seven sacred cities); built on the site where Lord Krishna is believed to have established his kingdom of Dwarka.',
    history: 'The current temple is believed to be 2,500 years old; the original temple was submerged in the sea. The present five-storey structure stands atop 72 pillars and was built during the Solanki period.',
    best_time_visit: 'October to March. Janmashtami celebrations are grandeur.',
    festivals: ['Janmashtami', 'Holi', 'Sharad Purnima'],
    contact_phone: '+91-2892-234819',
    website: null,
    image_url: '/src/assets/images/temple-somnath.jpg',
    tag: 'FEATURED',
    rating: 4.7,
    reviews: 17300,
  },
  {
    name: 'Amarnath Temple',
    deity: 'Lord Shiva',
    other_deities: [],
    category: 'Shiva',
    location_city: 'Pahalgam',
    location_state: 'Jammu & Kashmir',
    full_address: 'Amarnath Cave, Anantnag District, J&K 192101',
    pincode: '192101',
    latitude: 34.2133,
    longitude: 75.5013,
    nearest_railway: 'Anantnag Railway Station (55 km)',
    nearest_airport: 'Srinagar International Airport (141 km)',
    timings_general: '5:00 AM – 8:00 PM (Jun–Aug only)',
    timings_morning_aarti: '5:30 AM',
    timings_evening_aarti: '6:30 PM',
    timings_closed_on: 'Open only June to August (Yatra season)',
    entry_fee: 'Free (Yatra registration required)',
    dress_code: 'Warm clothing mandatory; trekking gear needed',
    special_darshan: 'Helicopter services from Baltal and Pahalgam',
    famous_for: 'Natural ice Shivalinga that grows and shrinks with the moon; situated at 3,888 m altitude; one of the most important Shiva shrines.',
    history: 'The cave shrine was rediscovered in the 15th century by a Muslim shepherd named Buta Malik. Pilgrimage records date back to the Bhrigu Samhita. The Shri Amarnathji Shrine Board (SASB) manages the Yatra.',
    best_time_visit: 'July to August (Yatra season). Book registration early on the SASB website.',
    festivals: ['Raksha Bandhan (Shravan Purnima - last day of Yatra)', 'Mahashivaratri'],
    contact_phone: '0194-2313009 (SASB)',
    website: 'https://shriamarnathjishrine.com',
    image_url: '/src/assets/images/temple-kashi.jpg',
    tag: 'LIVE',
    rating: 4.9,
    reviews: 28900,
  },
  {
    name: 'Shirdi Sai Baba Temple',
    alternate_name: 'Shirdi Saibaba Sansthan',
    deity: 'Sai Baba of Shirdi',
    other_deities: [],
    category: 'Other',
    location_city: 'Shirdi',
    location_state: 'Maharashtra',
    full_address: 'Shirdi, Ahmednagar, Maharashtra 423109',
    pincode: '423109',
    latitude: 19.7660,
    longitude: 74.4773,
    nearest_railway: 'Sainagar Shirdi Railway Station (1 km)',
    nearest_airport: 'Shirdi Airport (15 km)',
    timings_general: '4:00 AM – 11:00 PM',
    timings_morning_aarti: '4:30 AM (Kakad Aarti)',
    timings_evening_aarti: '8:00 PM (Shej Aarti)',
    timings_closed_on: 'Open all days',
    entry_fee: 'Free',
    dress_code: 'No specific dress code; modest attire recommended',
    special_darshan: 'VIP darshan pass ₹500; online darshan slot booking at sai.org.in',
    famous_for: 'Second most visited pilgrimage site in India after Tirupati; Sai Baba is revered by both Hindus and Muslims; the temple receives ₹500+ crore donations annually.',
    history: 'Sai Baba lived in Shirdi from 1858 until his death in 1918. The present temple complex was developed in the 20th century by the Shirdi Sai Baba Sansthan Trust and is one of the wealthiest religious trusts.',
    best_time_visit: 'Year-round. Ram Navami and Gurupurnima attract millions.',
    festivals: ['Ram Navami', 'Gurupurnima', 'Diwali', 'Vijayadasami'],
    contact_phone: '+91-2423-258770',
    website: 'https://www.sai.org.in',
    image_url: '/src/assets/images/temple-meenakshi.jpg',
    tag: 'POPULAR',
    rating: 4.8,
    reviews: 52300,
  },
  {
    name: 'Akshardham Temple Delhi',
    alternate_name: 'Swaminarayan Akshardham',
    deity: 'Lord Swaminarayan',
    other_deities: ['Akshar Purushottam', 'Lord Vishnu'],
    category: 'Vishnu',
    location_city: 'New Delhi',
    location_state: 'Delhi',
    full_address: 'NH 24, Noida Link Rd, New Delhi 110092',
    pincode: '110092',
    latitude: 28.6127,
    longitude: 77.2773,
    nearest_railway: 'Hazrat Nizamuddin (5 km)',
    nearest_airport: 'Indira Gandhi International Airport (16 km)',
    timings_general: '9:30 AM – 6:30 PM',
    timings_morning_aarti: '9:30 AM',
    timings_evening_aarti: '5:30 PM',
    timings_closed_on: 'Closed on Mondays',
    entry_fee: 'Complex free; exhibitions ₹170–250',
    dress_code: 'Traditional attire strongly preferred; no shorts or sleeveless',
    special_darshan: 'Water show Sahaj Anand ₹80; Audio Animatronics show ₹170',
    famous_for: 'Guinness World Record for largest Hindu temple complex; crafted from 234 ornately carved pillars and 20,000 statues; no steel was used in construction.',
    history: 'Inaugurated in 2005; built in just 5 years by 11,000 artisans and thousands of BAPS volunteers. The main monument features intricate carvings from pink Rajasthani sandstone and Italian marble.',
    best_time_visit: 'October to March. Diwali celebrations are spectacular.',
    festivals: ['Diwali', 'Ram Navami', 'Janmashtami'],
    contact_phone: '+91-11-43444344',
    website: 'https://akshardham.com/delhi',
    image_url: '/src/assets/images/temple-tirupati.jpg',
    tag: 'FEATURED',
    rating: 4.9,
    reviews: 67400,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// CSV COLUMN MAP  (adjust keys to match your Kaggle CSV headers)
// ─────────────────────────────────────────────────────────────────────────────
function csvRowToTemple(row, index) {
  return {
    name: row['Temple Name'] || row['name'] || `Temple ${index + 1}`,
    alternate_name: row['Also Known As'] || row['alternate_name'] || null,
    deity: row['Main Deity'] || row['deity'] || 'Unknown',
    other_deities: [],
    category: deriveCategory(row['Main Deity'] || row['deity'] || ''),
    location_city: row['City'] || row['city'] || '',
    location_state: row['State'] || row['state'] || '',
    full_address: row['Address'] || row['address'] || '',
    pincode: row['Pincode'] || row['pincode'] || null,
    latitude: parseFloat(row['Latitude'] || row['lat']) || null,
    longitude: parseFloat(row['Longitude'] || row['lng'] || row['long']) || null,
    nearest_railway: row['Nearest Railway'] || null,
    nearest_airport: row['Nearest Airport'] || null,
    timings_general: row['Timings'] || row['timings'] || '6:00 AM – 8:00 PM',
    timings_morning_aarti: row['Morning Aarti'] || null,
    timings_evening_aarti: row['Evening Aarti'] || null,
    timings_closed_on: row['Closed On'] || 'Open all days',
    entry_fee: row['Entry Fee'] || row['entry_fee'] || 'Free',
    dress_code: row['Dress Code'] || null,
    special_darshan: row['Special Darshan'] || null,
    famous_for: row['Famous For'] || row['description'] || '',
    history: row['History'] || row['history'] || '',
    best_time_visit: row['Best Time'] || row['best_time'] || 'October to March',
    festivals: (row['Festivals'] || '').split(',').map(s => s.trim()).filter(Boolean),
    contact_phone: row['Phone'] || row['phone'] || null,
    website: row['Website'] || row['website'] || null,
    image_url: row['Image URL'] || row['image'] || '/src/assets/images/hero-temple.jpg',
    tag: row['Tag'] || 'POPULAR',
    rating: parseFloat(row['Rating'] || row['rating']) || 4.5,
    reviews: parseInt(row['Reviews'] || row['reviews']) || 0,
  };
}

function deriveCategory(deity) {
  deity = deity.toLowerCase();
  if (deity.includes('shiva') || deity.includes('shankar') || deity.includes('mahadev')) return 'Shiva';
  if (deity.includes('vishnu') || deity.includes('krishna') || deity.includes('ram') || deity.includes('venkat')) return 'Vishnu';
  if (deity.includes('devi') || deity.includes('durga') || deity.includes('kali') || deity.includes('lakshmi') || deity.includes('saraswati') || deity.includes('parvati') || deity.includes('mata') || deity.includes('amman') || deity.includes('amma')) return 'Devi';
  if (deity.includes('ganesh') || deity.includes('ganesha') || deity.includes('vinayak')) return 'Other';
  return 'Other';
}

// ─────────────────────────────────────────────────────────────────────────────
// INSERT FUNCTION
// ─────────────────────────────────────────────────────────────────────────────
async function insertTemples(temples, client) {
  let inserted = 0;
  for (const t of temples) {
    try {
      await client.query(`
        INSERT INTO temples (
          name, alternate_name, deity, other_deities, category,
          location_city, location_state, full_address, pincode, latitude, longitude,
          nearest_railway, nearest_airport,
          timings_general, timings_morning_aarti, timings_evening_aarti, timings_closed_on,
          entry_fee, dress_code, special_darshan,
          famous_for, history, best_time_visit, festivals,
          contact_phone, website, image_url, tag, rating, reviews
        ) VALUES (
          $1,$2,$3,$4,$5,
          $6,$7,$8,$9,$10,$11,
          $12,$13,
          $14,$15,$16,$17,
          $18,$19,$20,
          $21,$22,$23,$24,
          $25,$26,$27,$28,$29,$30
        )
        ON CONFLICT DO NOTHING
      `, [
        t.name, t.alternate_name, t.deity, t.other_deities || [], t.category,
        t.location_city, t.location_state, t.full_address, t.pincode, t.latitude, t.longitude,
        t.nearest_railway, t.nearest_airport,
        t.timings_general, t.timings_morning_aarti, t.timings_evening_aarti, t.timings_closed_on,
        t.entry_fee, t.dress_code, t.special_darshan,
        t.famous_for, t.history, t.best_time_visit, t.festivals || [],
        t.contact_phone, t.website, t.image_url, t.tag, t.rating, t.reviews,
      ]);
      inserted++;
    } catch (err) {
      console.warn(`  ⚠️  Skipped "${t.name}": ${err.message}`);
    }
  }
  return inserted;
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────────────────────
async function seed() {
  const client = await pool.connect();
  try {
    const csvPath = path.join(__dirname, '../../data/temples.csv');
    let temples = [];

    if (fs.existsSync(csvPath)) {
      console.log(`📂 Found Kaggle CSV at ${csvPath} — parsing...`);
      const raw = fs.readFileSync(csvPath, 'utf-8');
      const rows = parse(raw, { columns: true, skip_empty_lines: true, trim: true });
      temples = rows.map((row, i) => csvRowToTemple(row, i));
      console.log(`   Parsed ${temples.length} rows from CSV`);
    } else {
      console.log('ℹ️  No Kaggle CSV found at data/temples.csv — using hardcoded seed data');
      console.log('   (Download from Kaggle and place as backend/data/temples.csv to use real data)');
      temples = HARDCODED_TEMPLES;
    }

    console.log(`\n🌱 Seeding ${temples.length} temples...`);
    const inserted = await insertTemples(temples, client);
    console.log(`✅ Seeded ${inserted} temples successfully\n`);

  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch(() => process.exit(1));
